### ISSUE TITLE
Json Parse Error when using Chinese in project name

### ISSUE THREAD

**Issue by Cospotato** [moranje/alfred-workflow-todoist#111]
### Description

Json parse error

### Steps to reproduce

1. Create a project in todoist with name '博客'
2. Alfred input 'todo xxx #博客'
3. See error

### Error logs

STEPS:

1. Open workflows tab in Alfred
2. Select `Alfred Workflow Todoist`
3. Select `Toggle debugging mode` in de upper right corner
4. Set logging to `All information` 5. Rerun query

Log:

```
[2019-04-22 10:49:39][ERROR: input.scriptfilter] JSON error: JSON text did not start with array or object and option to allow fragments not set. in JSON:
Error: invalid syntax at line 1 col 6:

  xxx #博客 
       ^

ALFRED WORKFLOW TODOIST
----------------------------------------
os: macOS 10.14.4
query: xxx #博客 
node.js: v11.3.0
alfred: 3.2
workflow: 5.8.1
Stack: Error: invalid syntax at line 1 col 6:

  xxx #博客 
       ^
    at Lexer._token (/Users/CosPotato/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.8FADB2CC-B41D-4139-BB39-35C12AC3A7C6/alfred-workflow-todoist.js:27422:13)
    at Lexer.next (/Users/CosPotato/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.8FADB2CC-B41D-4139-BB39-35C12AC3A7C6/alfred-workflow-todoist.js:27369:19)
    at Parser.feed (/Users/CosPotato/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.8FADB2CC-B41D-4139-BB39-35C12AC3A7C6/alfred-workflow-todoist.js:28075:30)
    at parser (/Users/CosPotato/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.8FADB2CC-B41D-4139-BB39-35C12AC3A7C6/alfred-workflow-todoist.js:28206:12)
    at Object.init (/Users/CosPotato/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.8FADB2CC-B41D-4139-BB39-35C12AC3A7C6/alfred-workflow-todoist.js:26889:23)
    at Stamp (/Users/CosPotato/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.8FADB2CC-B41D-4139-BB39-35C12AC3A7C6/alfred-workflow-todoist.js:6234:1207)
    at Object.create (/Users/CosPotato/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.8FADB2CC-B41D-4139-BB39-35C12AC3A7C6/alfred-workflow-todoist.js:39371:20)
    at Object.<anonymous> (/Users/CosPotato/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.8FADB2CC-B41D-4139-BB39-35C12AC3A7C6/alfred-workflow-todoist.js:39526:17)
    at Module._compile (internal/modules/cjs/loader.js:722:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:733:10)
```

**Comment by moranje** [comment]
Hmm I thought I had adjusted the parser to include all scripts. I will have
a look.

Op ma 22 apr. 2019 04:53 schreef CosPotato Lin <notifications@github.com>:

**Comment by Cospotato** [comment]
@moranje Thanks for your brilliant work!

**Comment by moranje** [comment]
I've created a fix but in order for the parser to accept the more elegant solution I've had to fix a bug  in one of the libraries I depend upon. I'll upload a fix as soon as that get's merged (https://github.com/no-context/moo/pull/124#issue-272380919).

Here's a preview:

<img width="631" alt="Schermafbeelding 2019-04-22 om 16 01 31" src="https://user-images.githubusercontent.com/666528/56504367-97170700-6518-11e9-9efc-e5c0b730154c.png">

**Comment by moranje** [comment]
I've changed my mind, here's a fix now
