### ISSUE TITLE
Creating tasks in projects with an emoticon at the beginning gives errors

### ISSUE THREAD

**Issue by primeminister** [moranje/alfred-workflow-todoist#112]
### Description

I have projects with emoticons in it. f.e.: "🦌 Personal". When creating a task it appends the square brackets but still gives errors when trying to create it.

### Steps to reproduce
1. Make test project with emoticon in it (through your mobile phone is easiest). Add the emoticon at the beginning of the project name.
2. Run workflow 'Create task' and add your project in Alfredt: 'todo test #' and select the project with emoticon 
3. look at the errros

### Expected behavior

It creates the task no matter if the project has an emoticon at the start of its name.

### Error logs

[15:59:31.859] Alfred Workflow Todoist[Script Filter] Queuing argument 't'
[15:59:31.883] Alfred Workflow Todoist[Script Filter] Queuing argument 'te'
[15:59:32.020] Alfred Workflow Todoist[Script Filter] Queuing argument 'tes'
[15:59:32.154] Alfred Workflow Todoist[Script Filter] Queuing argument 'test'
[15:59:32.183] Alfred Workflow Todoist[Script Filter] Script with argv '(null)' finished
[15:59:32.188] Alfred Workflow Todoist[Script Filter] {"items":[{"uid":"693e9af84d3dfcc71e640e005bdc5e2e","title":"CREATE: t","subtitle":"INBOX","icon":{"path":"icon.png"},"arg":"{\"content\":\"t\",\"priority\":1}","type":"default","valid":true}]}
[15:59:32.500] Alfred Workflow Todoist[Script Filter] Script with argv '(null)' finished
[15:59:32.506] Alfred Workflow Todoist[Script Filter] {"items":[{"uid":"693e9af84d3dfcc71e640e005bdc5e2e","title":"CREATE: test","subtitle":"INBOX","icon":{"path":"icon.png"},"arg":"{\"content\":\"test\",\"priority\":1}","type":"default","valid":true}]}
[15:59:33.850] Alfred Workflow Todoist[Script Filter] Queuing argument 'test '
[15:59:34.115] Alfred Workflow Todoist[Script Filter] Queuing argument 'test #'
[15:59:34.172] Alfred Workflow Todoist[Script Filter] Script with argv '(null)' finished
[15:59:34.176] Alfred Workflow Todoist[Script Filter] {"items":[{"uid":"693e9af84d3dfcc71e640e005bdc5e2e","title":"CREATE: test","subtitle":"INBOX","icon":{"path":"icon.png"},"arg":"{\"content\":\"test\",\"priority\":1}","type":"default","valid":true}]}
[15:59:34.368] Alfred Workflow Todoist[Script Filter] Queuing argument 'test #p'
[15:59:34.432] Alfred Workflow Todoist[Script Filter] Queuing argument 'test #pe'
[15:59:34.498] Alfred Workflow Todoist[Script Filter] Script with argv '(null)' finished
[15:59:34.502] Alfred Workflow Todoist[Script Filter] {"items":[{"uid":"693e9af84d3dfcc71e640e005bdc5e2e","title":"Inbox","subtitle":"Move task to Inbox","icon":{"path":"icon.png"},"type":"default","valid":false,"autocomplete":"test #Inbox "},{"uid":"693e9af84d3dfcc71e640e005bdc5e2e","title":"🦌 Personal","subtitle":"Move task to 🦌 Personal","icon":{"path":"icon.png"},"type":"default","valid":false,"autocomplete":"test #[🦌 Personal] "},{"uid":"693e9af84d3dfcc71e640e005bdc5e2e","title":"🚙 Jeep","subtitle":"Move task to 🚙 Jeep","icon":{"path":"icon.png"},"type":"default","valid":false,"autocomplete":"test #[🚙 Jeep] "},{"uid":"693e9af84d3dfcc71e640e005bdc5e2e","title":"🔩 Klussen","subtitle":"Move task to 🔩 Klussen","icon":{"path":"icon.png"},"type":"default","valid":false,"autocomplete":"test #[🔩 Klussen] "},{"uid":"693e9af84d3dfcc71e640e005bdc5e2e","title":"🥙 Boodschappen","subtitle":"Move task to 🥙 Boodschappen","icon":{"path":"icon.png"},"type":"default","valid":false,"autocomplete":"test #[🥙 Boodschappen] "},{"uid":"693e9af84d3dfcc71e640e005bdc5e2e","title":"GrandVision","subtitle":"Move task to GrandVision","icon":{"path":"icon.png"},"type":"default","valid":false,"autocomplete":"test #GrandVision "},{"uid":"693e9af84d3dfcc71e640e005bdc5e2e","title":"❔ Someday/Maybe","subtitle":"Move task to ❔ Someday/Maybe","icon":{"path":"icon.png"},"type":"default","valid":false,"autocomplete":"test #[❔ Someday/Maybe] "},{"uid":"693e9af84d3dfcc71e640e005bdc5e2e","title":"💡 Ideas","subtitle":"Move task to 💡 Ideas","icon":{"path":"icon.png"},"type":"default","valid":false,"autocomplete":"test #[💡 Ideas] "},{"uid":"693e9af84d3dfcc71e640e005bdc5e2e","title":"ReadWatch Later","subtitle":"Move task to ReadWatch Later","icon":{"path":"icon.png"},"type":"default","valid":false,"autocomplete":"test #[ReadWatch Later] "},{"uid":"693e9af84d3dfcc71e640e005bdc5e2e","title":"Tink","subtitle":"Move task to Tink","icon":{"path":"icon.png"},"type":"default","valid":false,"autocomplete":"test #Tink "}]}
[15:59:34.597] Alfred Workflow Todoist[Script Filter] Queuing argument 'test #per'
[15:59:34.787] Alfred Workflow Todoist[Script Filter] Queuing argument 'test #pers'
[15:59:34.836] Alfred Workflow Todoist[Script Filter] Script with argv '(null)' finished
[15:59:34.838] Alfred Workflow Todoist[Script Filter] {"items":[{"uid":"693e9af84d3dfcc71e640e005bdc5e2e","title":"🦌 Personal","subtitle":"Move task to 🦌 Personal","icon":{"path":"icon.png"},"type":"default","valid":false,"autocomplete":"test #[🦌 Personal] "},{"uid":"693e9af84d3dfcc71e640e005bdc5e2e","title":"🥙 Boodschappen","subtitle":"Move task to 🥙 Boodschappen","icon":{"path":"icon.png"},"type":"default","valid":false,"autocomplete":"test #[🥙 Boodschappen] "}]}
[15:59:35.154] Alfred Workflow Todoist[Script Filter] Script with argv '(null)' finished
[15:59:35.174] Alfred Workflow Todoist[Script Filter] {"items":[{"uid":"693e9af84d3dfcc71e640e005bdc5e2e","title":"🦌 Personal","subtitle":"Move task to 🦌 Personal","icon":{"path":"icon.png"},"type":"default","valid":false,"autocomplete":"test #[🦌 Personal] "}]}
[15:59:35.795] Alfred Workflow Todoist[Script Filter] Queuing argument 'test #[🦌 Personal] '
[15:59:41.308] Alfred Workflow Todoist[Script Filter] Script with argv '(null)' finished
[15:59:41.331] Alfred Workflow Todoist[Script Filter] Error: invalid syntax at line 1 col 8:

  test #[🦌 Personal] 
         ^

ALFRED WORKFLOW TODOIST
----------------------------------------
os: macOS 12.3.0
query: test #[🦌 Personal] 
node.js: v11.8.0
alfred: unknown
workflow: 5.6.5
Stack: Error: invalid syntax at line 1 col 8:

  test #[🦌 Personal] 
         ^
    at Lexer._token (/Users/charlie/Sync/Apps/Alfred.alfredpreferences/workflows/user.workflow.31A84382-D91F-4ED3-B309-566A153B3C5D/alfred-workflow-todoist.js:36581:13)
    at Lexer.next (/Users/charlie/Sync/Apps/Alfred.alfredpreferences/workflows/user.workflow.31A84382-D91F-4ED3-B309-566A153B3C5D/alfred-workflow-todoist.js:36528:19)
    at Parser.feed (/Users/charlie/Sync/Apps/Alfred.alfredpreferences/workflows/user.workflow.31A84382-D91F-4ED3-B309-566A153B3C5D/alfred-workflow-todoist.js:37229:30)
    at parser (/Users/charlie/Sync/Apps/Alfred.alfredpreferences/workflows/user.workflow.31A84382-D91F-4ED3-B309-566A153B3C5D/alfred-workflow-todoist.js:37360:12)
    at Object.init (/Users/charlie/Sync/Apps/Alfred.alfredpreferences/workflows/user.workflow.31A84382-D91F-4ED3-B309-566A153B3C5D/alfred-workflow-todoist.js:36048:23)
    at Stamp (/Users/charlie/Sync/Apps/Alfred.alfredpreferences/workflows/user.workflow.31A84382-D91F-4ED3-B309-566A153B3C5D/alfred-workflow-todoist.js:6241:1207)
    at Object.create (/Users/charlie/Sync/Apps/Alfred.alfredpreferences/workflows/user.workflow.31A84382-D91F-4ED3-B309-566A153B3C5D/alfred-workflow-todoist.js:46835:20)
    at Object.<anonymous> (/Users/charlie/Sync/Apps/Alfred.alfredpreferences/workflows/user.workflow.31A84382-D91F-4ED3-B309-566A153B3C5D/alfred-workflow-todoist.js:46953:19)
    at Module._compile (internal/modules/cjs/loader.js:736:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:747:10)

Log: 

```
ALFRED WORKFLOW TODOIST
----------------------------------------
os: macOS 10.14.5
query: {"content":"<title>","priority":1}
node.js: <version>
alfred: <version>
workflow: <version>
Stack: HTTPError: Response code 400 (Bad Request)
 ...
```

**Comment by moranje** [comment]
That's right, the workflow has a parser that doesn't include the unicode characters for emoticons. But if Todoist supports emoticons, the  workflow  should too. Do you happen to know if emoticons are supported within labels as well?

**Comment by primeminister** [comment]
Hi Martien, Yes it does. Is it changing the parser? Let me know if I can do something. I'm comfortable with Javascript but it has been a while...
<img width="127" alt="Screenshot 2019-07-29 at 07 57 26" src="https://user-images.githubusercontent.com/35230/62024867-acb26180-b1d6-11e9-9455-7aadbe979f16.png">

**Comment by moranje** [comment]
@primeminister Sure, it's the lexer. It's a matter of adding the Unicode ranges for emoticons to the lexer [here](https://github.com/moranje/alfred-workflow-todoist/blob/master/src/todoist/lexer.ts) if you'd like to take a stab at it.

**Comment by primeminister** [comment]
@moranje Man... that has been a while. I have no idea what you are doing there. I added a few unicodes to ALL_SCRIPT to test but it doesn't get picked up. Don't know if adding it to the end of beginning makes any difference. Maybe some hints? Dank! en nog bedankt voor de toffe workflow

**Comment by moranje** [comment]
I guess something along the lines of could work. SEPARATORS is the RegExp the lexer uses to match special strings. I don't want to be to permissive mainly because certain characters have special meaning in the context  of Todoist and the parser needs characters (whitespace, comma) to do it's matching. SEPERATORS is a bit of a misnomer at this point.

``` js
// /(?:\p{Letter}|\p{Number})+/u
const ALL_SCRIPTS = ...
const EMOTICONS = / \u27BF/
const SEPARATORS = new RegExp(`(?:${ALL_SCRIPTS.source}|${EMOTICONS.source}|_|-)+`)
```

**Comment by primeminister** [comment]
@moranje I added the emoticons (not unicode) and updated 1 test (zie fix above). 
I tried to do it through unicode chars, but that does not work with jstest (and more I think). Also having a space between the emoticon and name is not picked up by the regexp. f.i." 🚙 Car" instead of "🚙Car". Let me know what you think so I can improve and send you a PR

**Comment by moranje** [comment]
@primeminister Thanks for working on this, it's appreciated. You are right, the test suite is broken. I guess updated one of the deps a little carelessly. I'll try to fix that shortly. 

I have a special notation for adding project names with spaces. Try `#[🚙 Car]`. I might be able to schedule some time for this tomorrow, hopefully fixing the  tests.

**Comment by primeminister** [comment]
@moranje Yeah tried `#[🚙 Car]` already but fails:
`Unit: Lexer › should tokenize project with emoticon

    invalid syntax at line 1 col 3:

      #[🚙 Car]
        ^

      18 |   it('should tokenize project with emoticon', () => {
      19 |     lexer.reset('#[🚙 Car]')
    > 20 |     let tokens: any[] = Array.from(lexer)
         |                               ^
      21 |
      22 |     expect(tokens.map(token => token.type)).toEqual(['pound', 'name'])
      23 |   })

      at Lexer._token (node_modules/moo/moo.js:518:13)
      at Lexer.next (node_modules/moo/moo.js:465:19)
      at LexerIterator.next (node_modules/moo/moo.js:534:30)
          at Function.from (<anonymous>)
      at Object.<anonymous> (test/lexer.spec.ts:20:31)`

**Comment by moranje** [comment]
Ah I misunderstood. Replace the following line:

``` js
const WHITESPACE = new RegExp(`(?:${ALL_SCRIPTS.source}|_| |-)+`)
```

with

``` js
const WHITESPACE = new RegExp(`(?:${ALL_SCRIPTS.source}|${EMOTICONS.source}|_| |-)+`)
```

and you should be okay.

**Comment by moranje** [comment]
Did you you say you had a full unicode list of the emoji/emoticons?

**Comment by primeminister** [comment]
Works like a charm @moranje ! Nice work
