### ISSUE TITLE
Crash on Launching With Fresh Installation

### ISSUE THREAD

**Issue by breyerjs** [moranje/alfred-workflow-todoist#114]
### Steps to reproduce

1. Alfred input: `todo` or any other command
2. Click on: no click, just press space beyond `todo` and enter text
3. See error

### Expected behavior
I installed a fresh version of the workflow. I expected it to work as described in the `Usage`. Instead, when I enter `todo` into Alfred and press `<space>` the debugger registers the crash I've included below and the workflow exits (ie., alfred shows the default options of Google, Amazon, Wikipedia).

### Error logs

Log:
```Starting debug for 'Alfred Workflow Todoist'

[2019-08-07 18:22:47][ERROR: input.scriptfilter] Code 1: internal/modules/cjs/loader.js:573
    throw err;
    ^

Error: Cannot find module 'worker_threads'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:571:15)
    at Function.Module._load (internal/modules/cjs/loader.js:497:25)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/breyerjs/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.3C2707F8-57EE-42B1-AF9C-2F71E790A5DE/alfred-workflow-todoist.js:14:38)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
[2019-08-07 18:22:47][ERROR: input.scriptfilter] Code 1: internal/modules/cjs/loader.js:573
    throw err;
    ^

Error: Cannot find module 'worker_threads'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:571:15)
    at Function.Module._load (internal/modules/cjs/loader.js:497:25)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/breyerjs/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.3C2707F8-57EE-42B1-AF9C-2F71E790A5DE/alfred-workflow-todoist.js:14:38)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)```


```
ALFRED WORKFLOW TODOIST
----------------------------------------
os: macOS 10.14.4 (Mojave)
query: `todo `
node.js: 10.0.0
alfred: 3.8.2
workflow: 5.8.3
```

**Comment by moranje** [comment]
That's a bug, I'll have a look. Thanks for reporting.

Op do 8 aug. 2019 03:32 schreef Jackson Breyer <notifications@github.com>:

**Comment by moranje** [comment]
Are you able to update to the latest node.js just to see if that fixes it. I think one of the dependencies may rely on an newly introduces `web workers`.

**Comment by breyerjs** [comment]
I upgraded node to `12.8.0` and that fixed the issue. Thanks for the quick response!
