### ISSUE TITLE
Errors since updated Alfred

### ISSUE THREAD

**Issue by nickwild-999** [moranje/alfred-workflow-todoist#115]
### Description
No longer works. Think this may be concurrent with upgrading Alfred 

### Steps to reproduce
type todo and then any task

### Error logs

```
[09:09:17.853] Logging Stopped.
[09:09:44.236] Logging Started...
[09:09:55.183] Alfred Workflow Todoist[Script Filter] Queuing argument 's'
[09:09:55.392] Alfred Workflow Todoist[Script Filter] Script with argv '(null)' finished
[09:09:55.397] ERROR: Alfred Workflow Todoist[Script Filter] Code 1: internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'worker_threads'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/nickwild/Dropbox/Sync Folders/Alfred Sync/Alfred.alfredpreferences/workflows/user.workflow.D08D7736-7009-4F87-B49B-FD33C793FACA/alfred-workflow-todoist.js:14:38)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
```

**Comment by moranje** [comment]
I should update the minimum node version, which is 10.5 since I've updated one of the dependencies (not sure which one though). If you upgrade your nose before this should be fixed for now. Let me know if that helps.

**Comment by nickwild-999** [comment]
I am on Node 10.10 already. Might it be something else?

**Comment by moranje** [comment]
I don't think so, it's the same error as #114 had. Upgrading to the latest node.js (12.x) fixed the bug. Worker threads were added in node 10.5 but perhaps only behind an experimental flag. A quick fix would be upgrading to the latest node version. I would be willing to check what the earliest version of node is that has support for worker threads.

**Comment by moranje** [comment]
In case you care that the earliest version of node to allow you to run worker_threads without the experimental flag would be `11.7.0`

**Comment by nickwild-999** [comment]
Thanks @moranje I was keeping to Node 10, but bitten the bullet and upgraded to node latest and all is good. Thanks for a great enhancement to Alfred!
