### ISSUE TITLE
workflow stopped working :-(

### ISSUE THREAD

**Issue by smithers420** [moranje/alfred-workflow-todoist#116]
### Description

Probably since an API update on the todoist it seems that this workflow does not work anymore.

### Steps to reproduce

just try to use the workflow

### Expected behavior

it should work as expected with the normal features

**Comment by moranje** [comment]
Thanks for creating an issue, have you seen #114 and #115?

**Comment by mattyfew** [comment]
I am getting the same issue regarding the Todoist API Token.

**Comment by moranje** [comment]
@mattyfew That's not a lot for me to go on 😊. Can you describe what is happening? Did you try upgrading your node.js version to at least 11.5? If that doesn't help can you post an error log? Thanks

**Comment by milchquarz** [comment]
I have the same problem. This is how my error log looks like:


[19:25:33.938] Logging Started...
[19:25:43.412] Alfred Workflow Todoist[Script Filter] Queuing argument ''
[19:25:43.647] Alfred Workflow Todoist[Script Filter] Script with argv '(null)' finished
[19:25:43.652] ERROR: Alfred Workflow Todoist[Script Filter] Code 1: internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'worker_threads'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/axellambrette/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.2646C52E-F71E-4F44-8E3B-67F334C827A4/alfred-workflow-todoist.js:14:38)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)


Unfortunately I have no idea what that means. I hope you can help, since this is a wonderful workflow which I use all the time.

Cheers!

**Comment by moranje** [comment]
That means your node version is below 11.5 (at which version the module worker_treads was officially released). Try updating `node.js` to the latest version.
