### ISSUE TITLE
Error: Cannot find module 'worker_threads'

### ISSUE THREAD

**Issue by Code-Remote** [moranje/alfred-workflow-todoist#118]
### Description

Can't get the todo:setting token set because of error

### Steps to reproduce

1. Install workflow
2. type "todo:setting" 
3. See no behavior except in the Alfred debug logs

### Expected behavior

I would expect after typing "todo:setting" I would get an option between 'language', 'token'

### Error logs

Starting the debug button inside Alfred for  the 'Alfred Workflow Todoist' workflo

```
[2019-09-13 10:19:25][ERROR: input.scriptfilter] Code 1: internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'worker_threads'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/evert/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.EEFF0491-D3F9-4B4A-9CFE-4A3BA9C2251D/alfred-workflow-todoist.js:14:38)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
[2019-09-13 10:25:44][ERROR: input.scriptfilter] Code 1: internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'worker_threads'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/evert/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.EEFF0491-D3F9-4B4A-9CFE-4A3BA9C2251D/alfred-workflow-todoist.js:14:38)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

```
ALFRED WORKFLOW TODOIST
----------------------------------------
os: macOS  10.14.6 (18G95)
query: {todo:setting token}
node.js: v10.16.3
alfred: v3.8.3 [967]
workflow: v5.8.3
Stack: HTTPError: Response code 400 (Bad Request)
 ...
```

**Comment by mutdmour** [comment]
I fixed this by updating the node version to 12.10.0

**Comment by macinjoke** [comment]
I have encountered the same issue.

In node version 10, we need to execute node with `--experimental-worker` option to use `worker_threads`.

so if you use node 10, you need edit Alfred workflow manually. 

like `node --experimental-worker alfred-workflow-todoist.js create "{query}"` .

@moranje 
I think this should be documented somewhere.

**Comment by moranje** [comment]
@macinjoke I agree, haven't had any time to spend on this the last couple weeks. If you or anyone else is willing to submit a PR I'll commit it to master. Thanks

**Comment by macinjoke** [comment]
ok. I'll send a pull request. thank you.

**Comment by Code-Remote** [comment]
Awesome, thanks guys! Back to being productive again!
