### ISSUE TITLE
Issue potentially with either latest version of Todoist or Catalina 

### ISSUE THREAD

**Issue by Chris-Nicol** [moranje/alfred-workflow-todoist#122]
### Description

After updates to both macOS (Catalina) and the latest beta build of todoist I'm no longer able to create tasks from Alfred

### Steps to reproduce

1. Alfred input 'create task testing' 
2. See error - no error, just success message
3. Debug report:
![image](https://user-images.githubusercontent.com/792184/67239124-ce765a00-f44e-11e9-884d-db843528cbf4.png)

### Expected behavior

"Testing" is added to Inbox

### Error logs

Log:
[21:57:05.193] Logging Started...
[21:57:07.452] Alfred Workflow Todoist[Script Filter] Queuing argument '(null)'
[21:57:22.257] Alfred Workflow Todoist[Script Filter] Queuing argument '(null)'
[21:57:24.231] Alfred Workflow Todoist[Script Filter] Queuing argument ''
[21:57:24.444] Alfred Workflow Todoist[Script Filter] Script with argv '(null)' finished
[21:57:24.447] Alfred Workflow Todoist[Script Filter] {"items":[{"title":"Create new task - ","uid":"todoist_create_task","arg":"{\"labels\":[],\"priority\":1,\"project\":\"Inbox\",\"date\":\"\",\"task\":\"\"}","type":"default","valid":true,"autocomplete":"","icon":"icon.png","subtitle":"INBOX          ‼ 1          "},{"title":"Set project","uid":"bbc9730970b28397dce915182c8cda00","arg":"","type":"default","valid":false,"autocomplete":" #","icon":{"path":"project.png"},"subtitle":"Store task in a project, ex. #Work"},{"title":"Add label","uid":"26174b5e6f35917fff1bd408fedd6be8","arg":"","type":"default","valid":false,"autocomplete":" @","icon":{"path":"label.png"},"subtitle":"Add a label to this task, ex. @15min"},{"title":"Set priority","uid":"f6e80ca45bf8c7318816ee8ed557d3a3","arg":"","type":"default","valid":false,"autocomplete":" !!","icon":{"path":"priority.png"},"subtitle":"Set task priority, ex. !!3"},{"title":"Set date","uid":"6c8bb2104b71d1ce3c94d478ca05970c","arg":"","type":"default","valid":false,"autocomplete":" , ","icon":{"path":"date.png"},"subtitle":"Set a date using a todoist date string, ex. today"}]}
[21:57:25.910] Alfred Workflow Todoist[Script Filter] Queuing argument 't'
[21:57:26.011] Alfred Workflow Todoist[Script Filter] Queuing argument 'te'
[21:57:26.067] Alfred Workflow Todoist[Script Filter] Queuing argument 'tes'
[21:57:26.123] Alfred Workflow Todoist[Script Filter] Queuing argument 'test'
[21:57:26.127] Alfred Workflow Todoist[Script Filter] Script with argv '(null)' finished
[21:57:26.129] Alfred Workflow Todoist[Script Filter] {"items":[{"title":"Create new task - t","uid":"todoist_create_task","arg":"{\"labels\":[],\"priority\":1,\"project\":\"Inbox\",\"date\":\"\",\"task\":\"t\"}","type":"default","valid":true,"autocomplete":"t","icon":"icon.png","subtitle":"INBOX          ‼ 1          "},{"title":"Set project","uid":"bbc9730970b28397dce915182c8cda00","arg":"","type":"default","valid":false,"autocomplete":"t #","icon":{"path":"project.png"},"subtitle":"Store task in a project, ex. #Work"},{"title":"Add label","uid":"26174b5e6f35917fff1bd408fedd6be8","arg":"","type":"default","valid":false,"autocomplete":"t @","icon":{"path":"label.png"},"subtitle":"Add a label to this task, ex. @15min"},{"title":"Set priority","uid":"f6e80ca45bf8c7318816ee8ed557d3a3","arg":"","type":"default","valid":false,"autocomplete":"t !!","icon":{"path":"priority.png"},"subtitle":"Set task priority, ex. !!3"},{"title":"Set date","uid":"6c8bb2104b71d1ce3c94d478ca05970c","arg":"","type":"default","valid":false,"autocomplete":"t , ","icon":{"path":"date.png"},"subtitle":"Set a date using a todoist date string, ex. today"}]}
[21:57:26.282] Alfred Workflow Todoist[Script Filter] Queuing argument 'testi'
[21:57:26.336] Alfred Workflow Todoist[Script Filter] Script with argv '(null)' finished
[21:57:26.345] Alfred Workflow Todoist[Script Filter] {"items":[{"title":"Create new task - test","uid":"todoist_create_task","arg":"{\"labels\":[],\"priority\":1,\"project\":\"Inbox\",\"date\":\"\",\"task\":\"test\"}","type":"default","valid":true,"autocomplete":"test","icon":"icon.png","subtitle":"INBOX          ‼ 1          "},{"title":"Set project","uid":"bbc9730970b28397dce915182c8cda00","arg":"","type":"default","valid":false,"autocomplete":"test #","icon":{"path":"project.png"},"subtitle":"Store task in a project, ex. #Work"},{"title":"Add label","uid":"26174b5e6f35917fff1bd408fedd6be8","arg":"","type":"default","valid":false,"autocomplete":"test @","icon":{"path":"label.png"},"subtitle":"Add a label to this task, ex. @15min"},{"title":"Set priority","uid":"f6e80ca45bf8c7318816ee8ed557d3a3","arg":"","type":"default","valid":false,"autocomplete":"test !!","icon":{"path":"priority.png"},"subtitle":"Set task priority, ex. !!3"},{"title":"Set date","uid":"6c8bb2104b71d1ce3c94d478ca05970c","arg":"","type":"default","valid":false,"autocomplete":"test , ","icon":{"path":"date.png"},"subtitle":"Set a date using a todoist date string, ex. today"}]}
[21:57:26.358] Alfred Workflow Todoist[Script Filter] Queuing argument 'testin'
[21:57:26.415] Alfred Workflow Todoist[Script Filter] Queuing argument 'testing'
[21:57:26.563] Alfred Workflow Todoist[Script Filter] Script with argv '(null)' finished
[21:57:26.572] Alfred Workflow Todoist[Script Filter] {"items":[{"title":"Create new task - testi","uid":"todoist_create_task","arg":"{\"labels\":[],\"priority\":1,\"project\":\"Inbox\",\"date\":\"\",\"task\":\"testi\"}","type":"default","valid":true,"autocomplete":"testi","icon":"icon.png","subtitle":"INBOX          ‼ 1          "},{"title":"Set project","uid":"bbc9730970b28397dce915182c8cda00","arg":"","type":"default","valid":false,"autocomplete":"testi #","icon":{"path":"project.png"},"subtitle":"Store task in a project, ex. #Work"},{"title":"Add label","uid":"26174b5e6f35917fff1bd408fedd6be8","arg":"","type":"default","valid":false,"autocomplete":"testi @","icon":{"path":"label.png"},"subtitle":"Add a label to this task, ex. @15min"},{"title":"Set priority","uid":"f6e80ca45bf8c7318816ee8ed557d3a3","arg":"","type":"default","valid":false,"autocomplete":"testi !!","icon":{"path":"priority.png"},"subtitle":"Set task priority, ex. !!3"},{"title":"Set date","uid":"6c8bb2104b71d1ce3c94d478ca05970c","arg":"","type":"default","valid":false,"autocomplete":"testi , ","icon":{"path":"date.png"},"subtitle":"Set a date using a todoist date string, ex. today"}]}
[21:57:26.772] Alfred Workflow Todoist[Script Filter] Script with argv '(null)' finished
[21:57:26.785] Alfred Workflow Todoist[Script Filter] {"items":[{"title":"Create new task - testing","uid":"todoist_create_task","arg":"{\"labels\":[],\"priority\":1,\"project\":\"Inbox\",\"date\":\"\",\"task\":\"testing\"}","type":"default","valid":true,"autocomplete":"testing","icon":"icon.png","subtitle":"INBOX          ‼ 1          "},{"title":"Set project","uid":"bbc9730970b28397dce915182c8cda00","arg":"","type":"default","valid":false,"autocomplete":"testing #","icon":{"path":"project.png"},"subtitle":"Store task in a project, ex. #Work"},{"title":"Add label","uid":"26174b5e6f35917fff1bd408fedd6be8","arg":"","type":"default","valid":false,"autocomplete":"testing @","icon":{"path":"label.png"},"subtitle":"Add a label to this task, ex. @15min"},{"title":"Set priority","uid":"f6e80ca45bf8c7318816ee8ed557d3a3","arg":"","type":"default","valid":false,"autocomplete":"testing !!","icon":{"path":"priority.png"},"subtitle":"Set task priority, ex. !!3"},{"title":"Set date","uid":"6c8bb2104b71d1ce3c94d478ca05970c","arg":"","type":"default","valid":false,"autocomplete":"testing , ","icon":{"path":"date.png"},"subtitle":"Set a date using a todoist date string, ex. today"}]}
[21:57:30.175] Alfred Workflow Todoist[Script Filter] Processing complete
[21:57:30.191] Alfred Workflow Todoist[Script Filter] Passing output '{"labels":[],"priority":1,"project":"Inbox","date":"","task":"testing"}' to Run Script
[21:57:30.803] ERROR: Alfred Workflow Todoist[Run Script] undefined:1
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
^

SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at IncomingMessage.<anonymous> (.../Alfred.alfredpreferences/workflows/user.workflow.44F5CB65-E3FE-48DE-8AE4-2AEB3C85FB1E/js/request.js:20:22)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
[21:57:30.828] Alfred Workflow Todoist[Run Script] Processing complete
[21:57:30.829] Alfred Workflow Todoist[Run Script] Passing output '' to Junction
[21:57:30.830] Alfred Workflow Todoist[Junction] Processing complete
[21:57:30.830] Alfred Workflow Todoist[Junction] Passing output '' to Filter
[21:57:30.831] Alfred Workflow Todoist[Junction] Passing output '' to Filter
[21:57:30.832] Alfred Workflow Todoist[Filter] Processing complete
[21:57:30.833] Alfred Workflow Todoist[Filter] Passing output '' to Post Notification

```
ALFRED WORKFLOW TODOIST
----------------------------------------
os: macOS 10.15.0
query: {"content":"<title>","priority":1}
node.js: <version>
alfred: 4.0.5
workflow: 5.6.1
 ...
```

**Comment by moranje** [comment]
Update to the latest version of the workflow, todoist deprecated the beta version of the api. Latest release has you covered.

**Comment by stacksjb** [comment]
Thanks, I had the same issue, resolved it!

**Comment by stacksjb** [comment]
This can be closed :)
