### ISSUE TITLE
Cannot add a new task

### ISSUE THREAD

**Issue by alechp** [moranje/alfred-workflow-todoist#123]
### Description
Cannot add a new task.

Confirmed that API token is correct.

### Steps to reproduce

1. Alfred input 'todo hello'
2. Press "ENTER"
3. See error

### Expected behavior

"hello" is added to Todoist inbox

### Error logs

```sh
[16:47:09.697] Logging Started...
[16:47:12.763] Alfred Workflow Todoist[Script Filter] Queuing argument 'h'
[16:47:12.873] Alfred Workflow Todoist[Script Filter] Queuing argument 'he'
[16:47:13.046] Alfred Workflow Todoist[Script Filter] Script with argv '(null)' finished
[16:47:13.048] Alfred Workflow Todoist[Script Filter] {"items":[{"uid":"693e9af84d3dfcc71e640e005bdc5e2e","title":"CREATE: h","subtitle":"INBOX","icon":{"path":"icon.png"},"arg":"{\"content\":\"h\",\"priority\":1}","type":"default","valid":true}]}
[16:47:13.281] Alfred Workflow Todoist[Script Filter] Queuing argument 'hel'
[16:47:13.323] Alfred Workflow Todoist[Script Filter] Script with argv '(null)' finished
[16:47:13.325] Alfred Workflow Todoist[Script Filter] {"items":[{"uid":"693e9af84d3dfcc71e640e005bdc5e2e","title":"CREATE: he","subtitle":"INBOX","icon":{"path":"icon.png"},"arg":"{\"content\":\"he\",\"priority\":1}","type":"default","valid":true}]}
[16:47:13.419] Alfred Workflow Todoist[Script Filter] Queuing argument 'hell'
[16:47:13.577] Alfred Workflow Todoist[Script Filter] Queuing argument 'hello'
[16:47:13.598] Alfred Workflow Todoist[Script Filter] Script with argv '(null)' finished
[16:47:13.600] Alfred Workflow Todoist[Script Filter] {"items":[{"uid":"693e9af84d3dfcc71e640e005bdc5e2e","title":"CREATE: hel","subtitle":"INBOX","icon":{"path":"icon.png"},"arg":"{\"content\":\"hel\",\"priority\":1}","type":"default","valid":true}]}
[16:47:13.867] Alfred Workflow Todoist[Script Filter] Script with argv '(null)' finished
[16:47:13.871] Alfred Workflow Todoist[Script Filter] {"items":[{"uid":"693e9af84d3dfcc71e640e005bdc5e2e","title":"CREATE: hello","subtitle":"INBOX","icon":{"path":"icon.png"},"arg":"{\"content\":\"hello\",\"priority\":1}","type":"default","valid":true}]}
[16:47:14.506] Alfred Workflow Todoist[Script Filter] Processing complete
[16:47:14.512] Alfred Workflow Todoist[Script Filter] Passing output '{"content":"hello","priority":1}' to Run Script
[16:47:20.456] Alfred Workflow Todoist[Run Script] Processing complete
[16:47:20.460] Alfred Workflow Todoist[Run Script] Passing output 'HTTPError: Response code 410 (Gone)

ALFRED WORKFLOW TODOIST
----------------------------------------
os: macOS 13.0.0
query: {"content":"hello","priority":1}
node.js: v12.12.0
alfred: unknown
workflow: 5.6.4
Stack: HTTPError: Response code 410 (Gone)
    at EventEmitter.<anonymous> (/Users/alechp/Code/alechp/.repositories/config-backup/Alfred/Alfred.alfredpreferences/workflows/user.workflow.D9C55F89-3A91-486A-BB00-967FCB35341C/alfred-workflow-todoist.js:41004:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
' to Debug
[16:47:20.462] Alfred Workflow Todoist[Debug] 'HTTPError: Response code 410 (Gone)

ALFRED WORKFLOW TODOIST
----------------------------------------
os: macOS 13.0.0
query: {"content":"hello","priority":1}
node.js: v12.12.0
alfred: unknown
workflow: 5.6.4
Stack: HTTPError: Response code 410 (Gone)
    at EventEmitter.<anonymous> (/Users/alechp/Code/alechp/.repositories/config-backup/Alfred/Alfred.alfredpreferences/workflows/user.workflow.D9C55F89-3A91-486A-BB00-967FCB35341C/alfred-workflow-todoist.js:41004:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
', {}
[16:48:23.071] Alfred Workflow Todoist[Script Filter] Queuing argument 'H'
[16:48:23.351] Alfred Workflow Todoist[Script Filter] Queuing argument 'He'
[16:48:23.368] Alfred Workflow Todoist[Script Filter] Script with argv '(null)' finished
[16:48:23.369] Alfred Workflow Todoist[Script Filter] {"items":[{"uid":"693e9af84d3dfcc71e640e005bdc5e2e","title":"CREATE: H","subtitle":"INBOX","icon":{"path":"icon.png"},"arg":"{\"content\":\"H\",\"priority\":1}","type":"default","valid":true}]}
[16:48:23.479] Alfred Workflow Todoist[Script Filter] Queuing argument 'Hel'
[16:48:23.610] Alfred Workflow Todoist[Script Filter] Queuing argument 'Hell'
[16:48:23.654] Alfred Workflow Todoist[Script Filter] Script with argv '(null)' finished
[16:48:23.668] Alfred Workflow Todoist[Script Filter] {"items":[{"uid":"693e9af84d3dfcc71e640e005bdc5e2e","title":"CREATE: He","subtitle":"INBOX","icon":{"path":"icon.png"},"arg":"{\"content\":\"He\",\"priority\":1}","type":"default","valid":true}]}
[16:48:23.783] Alfred Workflow Todoist[Script Filter] Queuing argument 'Hello'
[16:48:23.955] Alfred Workflow Todoist[Script Filter] Script with argv '(null)' finished
[16:48:23.976] Alfred Workflow Todoist[Script Filter] {"items":[{"uid":"693e9af84d3dfcc71e640e005bdc5e2e","title":"CREATE: Hell","subtitle":"INBOX","icon":{"path":"icon.png"},"arg":"{\"content\":\"Hell\",\"priority\":1}","type":"default","valid":true}]}
[16:48:23.997] Alfred Workflow Todoist[Script Filter] Processing complete
[16:48:23.999] Alfred Workflow Todoist[Script Filter] Passing output '{"content":"Hell","priority":1}' to Run Script
[16:48:29.877] Alfred Workflow Todoist[Run Script] Processing complete
[16:48:29.894] Alfred Workflow Todoist[Run Script] Passing output 'HTTPError: Response code 410 (Gone)

ALFRED WORKFLOW TODOIST
----------------------------------------
os: macOS 13.0.0
query: {"content":"Hell","priority":1}
node.js: v12.12.0
alfred: unknown
workflow: 5.6.4
Stack: HTTPError: Response code 410 (Gone)
    at EventEmitter.<anonymous> (/Users/alechp/Code/alechp/.repositories/config-backup/Alfred/Alfred.alfredpreferences/workflows/user.workflow.D9C55F89-3A91-486A-BB00-967FCB35341C/alfred-workflow-todoist.js:41004:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
' to Debug
[16:48:29.896] Alfred Workflow Todoist[Debug] 'HTTPError: Response code 410 (Gone)

ALFRED WORKFLOW TODOIST
----------------------------------------
os: macOS 13.0.0
query: {"content":"Hell","priority":1}
node.js: v12.12.0
alfred: unknown
workflow: 5.6.4
Stack: HTTPError: Response code 410 (Gone)
    at EventEmitter.<anonymous> (/Users/alechp/Code/alechp/.repositories/config-backup/Alfred/Alfred.alfredpreferences/workflows/user.workflow.D9C55F89-3A91-486A-BB00-967FCB35341C/alfred-workflow-todoist.js:41004:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
', {}
[16:48:32.922] Alfred Workflow Todoist[Script Filter] Queuing argument 'H'
[16:48:32.992] Alfred Workflow Todoist[Script Filter] Queuing argument 'He'
[16:48:33.129] Alfred Workflow Todoist[Script Filter] Queuing argument 'Hel'
[16:48:33.206] Alfred Workflow Todoist[Script Filter] Script with argv '(null)' finished
[16:48:33.223] Alfred Workflow Todoist[Script Filter] {"items":[{"uid":"693e9af84d3dfcc71e640e005bdc5e2e","title":"CREATE: H","subtitle":"INBOX","icon":{"path":"icon.png"},"arg":"{\"content\":\"H\",\"priority\":1}","type":"default","valid":true}]}
[16:48:33.258] Alfred Workflow Todoist[Script Filter] Queuing argument 'Hell'
[16:48:33.408] Alfred Workflow Todoist[Script Filter] Queuing argument 'Hello'
[16:48:33.475] Alfred Workflow Todoist[Script Filter] Script with argv '(null)' finished
[16:48:33.494] Alfred Workflow Todoist[Script Filter] {"items":[{"uid":"693e9af84d3dfcc71e640e005bdc5e2e","title":"CREATE: Hel","subtitle":"INBOX","icon":{"path":"icon.png"},"arg":"{\"content\":\"Hel\",\"priority\":1}","type":"default","valid":true}]}
[16:48:33.747] Alfred Workflow Todoist[Script Filter] Script with argv '(null)' finished
[16:48:33.753] Alfred Workflow Todoist[Script Filter] {"items":[{"uid":"693e9af84d3dfcc71e640e005bdc5e2e","title":"CREATE: Hello","subtitle":"INBOX","icon":{"path":"icon.png"},"arg":"{\"content\":\"Hello\",\"priority\":1}","type":"default","valid":true}]}
[16:48:34.003] Alfred Workflow Todoist[Script Filter] Processing complete
[16:48:34.010] Alfred Workflow Todoist[Script Filter] Passing output '{"content":"Hello","priority":1}' to Run Script
[16:48:35.923] Alfred Workflow Todoist[Run Script] Processing complete
[16:48:35.931] Alfred Workflow Todoist[Run Script] Passing output 'HTTPError: Response code 410 (Gone)

ALFRED WORKFLOW TODOIST
----------------------------------------
os: macOS 13.0.0
query: {"content":"Hello","priority":1}
node.js: v12.12.0
alfred: unknown
workflow: 5.6.4
Stack: HTTPError: Response code 410 (Gone)
    at EventEmitter.<anonymous> (/Users/alechp/Code/alechp/.repositories/config-backup/Alfred/Alfred.alfredpreferences/workflows/user.workflow.D9C55F89-3A91-486A-BB00-967FCB35341C/alfred-workflow-todoist.js:41004:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
' to Debug
[16:48:35.933] Alfred Workflow Todoist[Debug] 'HTTPError: Response code 410 (Gone)

ALFRED WORKFLOW TODOIST
----------------------------------------
os: macOS 13.0.0
query: {"content":"Hello","priority":1}
node.js: v12.12.0
alfred: unknown
workflow: 5.6.4
Stack: HTTPError: Response code 410 (Gone)
    at EventEmitter.<anonymous> (/Users/alechp/Code/alechp/.repositories/config-backup/Alfred/Alfred.alfredpreferences/workflows/user.workflow.D9C55F89-3A91-486A-BB00-967FCB35341C/alfred-workflow-todoist.js:41004:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
', {}```

### Additional context

Add any other context about the problem here.

**Comment by moranje** [comment]
Update to the latest version of the workflow. Todoist deprecated the beta version of the api. The latest version has you covered.
