### ISSUE TITLE
ToDoist API give back error from cloudfront (401) Gone

### ISSUE THREAD

**Issue by Henry31** [moranje/alfred-workflow-todoist#127]
### Description

I just installed the alfred workflow for todoist for the first time. After adding the token to the settings I want to add a task to my inbox, but this is not working.

### Steps to reproduce

1. Alfred input 'todo testtask'
2. Click on 'return'
3. See error

### Expected behavior

normally it should add a new task to my inbox

### Error logs

```
ALFRED WORKFLOW TODOIST
----------------------------------------
os: macOS
query: 
node.js: v10.16.0
alfred: unknown
workflow: 5.6.1
Stack: HTTPError: Response code 410 (Gone)
    at EventEmitter.emitter.on (/Users/henryauffahrt/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.08AD33A3-711C-44AC-8D73-E86CD9EEC173/alfred-workflow-todoist.js:40858:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[12:52:03.737] Alfred Workflow Todoist[Script Filter] Queuing argument 't'
[12:52:03.904] Alfred Workflow Todoist[Script Filter] Queuing argument 'te'
[12:52:04.008] Alfred Workflow Todoist[Script Filter] Queuing argument 'tes'
[12:52:04.082] Alfred Workflow Todoist[Script Filter] Queuing argument 'test'
[12:52:04.095] Alfred Workflow Todoist[Script Filter] Script with argv '(null)' finished
[12:52:04.097] Alfred Workflow Todoist[Script Filter] {"items":[{"arg":"{\"content\":\"t\",\"priority\":1}","type":"default","valid":true,"autocomplete":"","title":"CREATE: t","subtitle":"INBOX","icon":{"path":"icon.png"},"uid":"4bac8c02b9f5e1a472d96ceb0c29cc7e"}]}
[12:52:04.296] Alfred Workflow Todoist[Script Filter] Queuing argument 'tests'
[12:52:04.461] Alfred Workflow Todoist[Script Filter] Script with argv '(null)' finished
[12:52:04.476] Alfred Workflow Todoist[Script Filter] {"items":[{"arg":"{\"content\":\"test\",\"priority\":1}","type":"default","valid":true,"autocomplete":"","title":"CREATE: test","subtitle":"INBOX","icon":{"path":"icon.png"},"uid":"4ce68bb3c27ed401d87a633aacd0adf2"}]}
[12:52:04.504] Alfred Workflow Todoist[Script Filter] Queuing argument 'testst'
[12:52:04.835] Alfred Workflow Todoist[Script Filter] Script with argv '(null)' finished
[12:52:04.851] Alfred Workflow Todoist[Script Filter] {"items":[{"arg":"{\"content\":\"tests\",\"priority\":1}","type":"default","valid":true,"autocomplete":"","title":"CREATE: tests","subtitle":"INBOX","icon":{"path":"icon.png"},"uid":"28aa75cded2bfaec7ddf3001de11ee2d"}]}
[12:52:04.912] Alfred Workflow Todoist[Script Filter] Queuing argument 'tests'
[12:52:05.042] Alfred Workflow Todoist[Script Filter] Queuing argument 'test'
[12:52:05.152] Alfred Workflow Todoist[Script Filter] Queuing argument 'testt'
[12:52:05.205] Alfred Workflow Todoist[Script Filter] Script with argv '(null)' finished
[12:52:05.226] Alfred Workflow Todoist[Script Filter] {"items":[{"arg":"{\"content\":\"testst\",\"priority\":1}","type":"default","valid":true,"autocomplete":"","title":"CREATE: testst","subtitle":"INBOX","icon":{"path":"icon.png"},"uid":"f57e605473648bef3e56f3f3c7410003"}]}
[12:52:05.408] Alfred Workflow Todoist[Script Filter] Queuing argument 'testta'
[12:52:05.564] Alfred Workflow Todoist[Script Filter] Script with argv '(null)' finished
[12:52:05.580] Alfred Workflow Todoist[Script Filter] {"items":[{"arg":"{\"content\":\"testt\",\"priority\":1}","type":"default","valid":true,"autocomplete":"","title":"CREATE: testt","subtitle":"INBOX","icon":{"path":"icon.png"},"uid":"b34ee95fff4c2a1b1271bdebbb7425dd"}]}
[12:52:05.582] Alfred Workflow Todoist[Script Filter] Queuing argument 'testtas'
[12:52:05.792] Alfred Workflow Todoist[Script Filter] Queuing argument 'testtask'
[12:52:05.939] Alfred Workflow Todoist[Script Filter] Script with argv '(null)' finished
[12:52:05.959] Alfred Workflow Todoist[Script Filter] {"items":[{"arg":"{\"content\":\"testta\",\"priority\":1}","type":"default","valid":true,"autocomplete":"","title":"CREATE: testta","subtitle":"INBOX","icon":{"path":"icon.png"},"uid":"8d1673dabe932059615c4a4e90815062"}]}
[12:52:06.474] Alfred Workflow Todoist[Script Filter] Processing complete
[12:52:06.497] Alfred Workflow Todoist[Script Filter] Passing output '{"content":"testta","priority":1}' to Run Script
[12:52:12.537] Alfred Workflow Todoist[Run Script] Processing complete
[12:52:12.557] Alfred Workflow Todoist[Run Script] Passing output 'Error log [Arguments] {
  '0':
   { HTTPError: Response code 410 (Gone)
       at EventEmitter.emitter.on (/Users/henryauffahrt/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.08AD33A3-711C-44AC-8D73-E86CD9EEC173/alfred-workflow-todoist.js:40858:19)
       at process._tickCallback (internal/process/next_tick.js:68:7)
     name: 'HTTPError',
     host: undefined,
     hostname: 'beta.todoist.com',
     method: 'GET',
     path: '/API/v8/projects',
     socketPath: undefined,
     protocol: 'https:',
     url: 'https://beta.todoist.com/API/v8/projects',
     statusCode: 410,
     statusMessage: 'Gone',
     headers:
      { 'content-type': 'text/plain; charset=utf-8',
        'content-length': '109',
        connection: 'close',
        server: 'awselb/2.0',
        date: 'Fri, 20 Dec 2019 11:52:07 GMT',
        'x-cache': 'Error from cloudfront',
        via:
         '1.1 420810dc8ca5cb74b64cae9e4b264cc9.cloudfront.net (CloudFront)',
        'x-amz-cf-pop': 'FRA54',
        'x-amz-cf-id': '5ruYvkwT0pW0AXB3ByXeCe_7DDodVnRKnsx2E9XrgbMvSUsURNUd9A==' } } }
HTTPError: Response code 410 (Gone)

ALFRED WORKFLOW TODOIST
----------------------------------------
os: macOS
query: {"content":"testta","priority":1}
node.js: v10.16.0
alfred: unknown
workflow: 5.6.1
Stack: HTTPError: Response code 410 (Gone)
    at EventEmitter.emitter.on (/Users/henryauffahrt/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.08AD33A3-711C-44AC-8D73-E86CD9EEC173/alfred-workflow-todoist.js:40858:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
' to Debug
[12:52:12.560] Alfred Workflow Todoist[Debug] 'Error log [Arguments] {
  '0':
   { HTTPError: Response code 410 (Gone)
       at EventEmitter.emitter.on (/Users/henryauffahrt/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.08AD33A3-711C-44AC-8D73-E86CD9EEC173/alfred-workflow-todoist.js:40858:19)
       at process._tickCallback (internal/process/next_tick.js:68:7)
     name: 'HTTPError',
     host: undefined,
     hostname: 'beta.todoist.com',
     method: 'GET',
     path: '/API/v8/projects',
     socketPath: undefined,
     protocol: 'https:',
     url: 'https://beta.todoist.com/API/v8/projects',
     statusCode: 410,
     statusMessage: 'Gone',
     headers:
      { 'content-type': 'text/plain; charset=utf-8',
        'content-length': '109',
        connection: 'close',
        server: 'awselb/2.0',
        date: 'Fri, 20 Dec 2019 11:52:07 GMT',
        'x-cache': 'Error from cloudfront',
        via:
         '1.1 420810dc8ca5cb74b64cae9e4b264cc9.cloudfront.net (CloudFront)',
        'x-amz-cf-pop': 'FRA54',
        'x-amz-cf-id': '5ruYvkwT0pW0AXB3ByXeCe_7DDodVnRKnsx2E9XrgbMvSUsURNUd9A==' } } }
HTTPError: Response code 410 (Gone)

ALFRED WORKFLOW TODOIST
----------------------------------------
os: macOS
query: {"content":"testta","priority":1}
node.js: v10.16.0
alfred: unknown
workflow: 5.6.1
Stack: HTTPError: Response code 410 (Gone)
    at EventEmitter.emitter.on (/Users/henryauffahrt/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.08AD33A3-711C-44AC-8D73-E86CD9EEC173/alfred-workflow-todoist.js:40858:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
', {}
```

### Additional context

Thanks a lot for your help in advance! I'd love to use todoist through Alfred :)

**Comment by moranje** [comment]
Use the latest version. Todoist deprecated their V8 API which the version you are using utilizes. Update and you should be fine.
