### ISSUE TITLE
Todos command crashes on unknown project name

### ISSUE THREAD

**Issue by kellyarwine** [moranje/alfred-workflow-todoist#160]
### Description

Thank you for creating this!  I'm excited to find this workflow.  I configured it via the instructions.  Checked all configuration settings, they all are set.  Try to log a task and get an error (see below).

### Steps to reproduce

1. Alfred input 'todo test'
2. Press 'Enter'
3. See error in console.

### Error logs

STEPS:

1. Open workflows tab in Alfred
2. Select `Alfred Workflow Todoist`
3. Select `Toggle debugging mode` in de upper right corner
4. Set logging to `All information` 5. Rerun query

Log:

```ALFRED WORKFLOW TODOIST
----------------------------------------
os: macOS
query: {"content":"working","priority":1}
node.js: v13.8.0
alfred: unknown
workflow: 5.6.1
Stack: HTTPError: Response code 410 (Gone)
    at EventEmitter.<anonymous> (/Users/kellyarwine/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.B6EAF5D0-B853-407A-9A88-8CDCEEED19D3/alfred-workflow-todoist.js:40858:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
', {}```

### Additional context

Operating System:  macOS Catalina
Workflow Version:  5.6.1
Node Version:  v13.8.0

Installed Node via Homebrew.  Read over the README 3 times and followed all of the steps (symlink, node_path) but still can't get it to work.

**Comment by moranje** [comment]
I can see you are using an outdated version of the workflow. I would recommend using the latest beta (6.0.0-beta.1). You can find it on the release tab on github.

Martien

**Comment by kellyarwine** [comment]
Awesome.  Thanks for the help.  I updated the new version of the workflow.  Logging a todo item works but `todos` does not work.  Here's the output:
```[11:40:42.500] Alfred Workflow Todoist[Script Filter] Queuing argument ''
[11:40:42.891] Alfred Workflow Todoist[Script Filter] Script with argv '(null)' finished
[11:40:42.894] STDERR: Alfred Workflow Todoist[Script Filter] [ERROR] TypeError: Cannot read property 'name' of undefined
    at nv (/Users/kellyarwine/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.B6EAF5D0-B853-407A-9A88-8CDCEEED19D3/alfred-workflow-todoist.js:29:321114)
    at async /Users/kellyarwine/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.B6EAF5D0-B853-407A-9A88-8CDCEEED19D3/alfred-workflow-todoist.js:29:324141
    at async Promise.all (index 0)
    at async iv (/Users/kellyarwine/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.B6EAF5D0-B853-407A-9A88-8CDCEEED19D3/alfred-workflow-todoist.js:29:325884)
[11:40:42.895] Alfred Workflow Todoist[Script Filter] {
  "items": [
    {
      "title": "Oops, something is not right",
      "subtitle": "Create a bug report",
      "icon": {
        "path": "icon.png"
      },
      "arg": "{\"name\":\"openUrl\",\"args\":\"https://github.com/moranje/alfred-workflow-todoist/issues/new?body=%23%23%23+Description%0A%0A%3CA+clear+and+concise+description+of+what+the+bug+is.%3E%0A%0A%23%23%23+Steps+to+reproduce+behavior%0A%0A%3CPlease+describe+what+you+did+here.%3E%0A%0A%23%23%23+Expected+behavior%0A%0A%3CA+clear+and+concise+description+of+what+you+expected+to+happen.%3E%0A%0A%23%23%23+Error+logs%0A%0AALFRED+WORKFLOW+TODOIST%0A----------------------------------------%0A_Title_%3A+TypeError%0A_Description_%3A+Cannot+read+property+%27name%27+of+undefined%0A%0A_OS_%3A+macOS+10.15.2%0A_Query_%3A+%0A_Node.js_%3A+v13.8.0%0A_Alfred_%3A+4.0.8%0A_Workflow_%3A+6.0.0-beta.1%0A_Workflow-id_%3A+user.workflow.B6EAF5D0-B853-407A-9A88-8CDCEEED19D3%0A%0A_Stack_%3A+TypeError%3A+Cannot+read+property+%27name%27+of+undefined%0A++++at+nv+%28%2FUsers%2Fkellyarwine%2FLibrary%2FApplication+Support%2FAlfred%2FAlfred.alfredpreferences%2Fworkflows%2Fuser.workflow.B6EAF5D0-B853-407A-9A88-8CDCEEED19D3%2Falfred-workflow-todoist.js%3A29%3A321114%29%0A++++at+async+%2FUsers%2Fkellyarwine%2FLibrary%2FApplication+Support%2FAlfred%2FAlfred.alfredpreferences%2Fworkflows%2Fuser.workflow.B6EAF5D0-B853-407A-9A88-8CDCEEED19D3%2Falfred-workflow-todoist.js%3A29%3A324141%0A++++at+async+Promise.all+%28index+0%29%0A++++at+async+iv+%28%2FUsers%2Fkellyarwine%2FLibrary%2FApplication+Support%2FAlfred%2FAlfred.alfredpreferences%2Fworkflows%2Fuser.workflow.B6EAF5D0-B853-407A-9A88-8CDCEEED19D3%2Falfred-workflow-todoist.js%3A29%3A325884%29&title=%5BBug%5D+TypeError%3A+Cannot+read+property+%27name%27+of+undefined\"}",
      "type": "default",
      "valid": true,
      "quicklookurl": "https://github.com/moranje/alfred-workflow-todoist/issues/new?body=%23%23%23+Description%0A%0A%3CA+clear+and+concise+description+of+what+the+bug+is.%3E%0A%0A%23%23%23+Steps+to+reproduce+behavior%0A%0A%3CPlease+describe+what+you+did+here.%3E%0A%0A%23%23%23+Expected+behavior%0A%0A%3CA+clear+and+concise+description+of+what+you+expected+to+happen.%3E%0A%0A%23%23%23+Error+logs%0A%0AALFRED+WORKFLOW+TODOIST%0A----------------------------------------%0A_Title_%3A+TypeError%0A_Description_%3A+Cannot+read+property+%27name%27+of+undefined%0A%0A_OS_%3A+macOS+10.15.2%0A_Query_%3A+%0A_Node.js_%3A+v13.8.0%0A_Alfred_%3A+4.0.8%0A_Workflow_%3A+6.0.0-beta.1%0A_Workflow-id_%3A+user.workflow.B6EAF5D0-B853-407A-9A88-8CDCEEED19D3%0A%0A_Stack_%3A+TypeError%3A+Cannot+read+property+%27name%27+of+undefined%0A++++at+nv+%28%2FUsers%2Fkellyarwine%2FLibrary%2FApplication+Support%2FAlfred%2FAlfred.alfredpreferences%2Fworkflows%2Fuser.workflow.B6EAF5D0-B853-407A-9A88-8CDCEEED19D3%2Falfred-workflow-todoist.js%3A29%3A321114%29%0A++++at+async+%2FUsers%2Fkellyarwine%2FLibrary%2FApplication+Support%2FAlfred%2FAlfred.alfredpreferences%2Fworkflows%2Fuser.workflow.B6EAF5D0-B853-407A-9A88-8CDCEEED19D3%2Falfred-workflow-todoist.js%3A29%3A324141%0A++++at+async+Promise.all+%28index+0%29%0A++++at+async+iv+%28%2FUsers%2Fkellyarwine%2FLibrary%2FApplication+Support%2FAlfred%2FAlfred.alfredpreferences%2Fworkflows%2Fuser.workflow.B6EAF5D0-B853-407A-9A88-8CDCEEED19D3%2Falfred-workflow-todoist.js%3A29%3A325884%29&title=%5BBug%5D+TypeError%3A+Cannot+read+property+%27name%27+of+undefined"
    }
  ]
}```

Any help you could provide?

**Comment by moranje** [comment]
Yup you caught a bug that I've tried to squash before, any chance you can provide the query that caused it? Also that link is meant to make it easy to report a bug, it should save you a little time, try it to see what I mean ;-). I'll post a fix within a day or two. Let me know if it fixes things for you.

Martien

**Comment by kellyarwine** [comment]
Oh neat.  I think I understand the link.  Maybe "Click here to log a bug" would be a better CTA?  I was simply typing "todos" and got the error.  No arguments.

**Comment by kellyarwine** [comment]
Nice.  Just tried the link to the bug.  Brilliant.

**Comment by moranje** [comment]
I can't reproduce the error in any way on my machine. I can't figure out what would cause it either. I've created a debug version that should print out an id of the offending project or task, would you mind running it on your machine to see if this produces a more helpful error? If you just get an an id back can you tell met the name of the project it belongs to?

You can find the name by pasting the id in after the following url `https://todoist.com/app#project%2F` + `<id>`.

Use the zip file rename it from `Alfred Workflow Todoist.zip` to `Alfred Workflow Todoist.alfredworkflow` (Github doesn't allow uploading files with `.alfredworkflow` extensions)

Thanks for helping out. 

Martien


[Alfred Workflow Todoist.zip](https://github.com/moranje/alfred-workflow-todoist/files/4289551/Alfred.Workflow.Todoist.zip)

**Comment by kellyarwine** [comment]
Hi there.  Back from a bit of time off.  Here's the logging I received:

```[11:18:42.236] Logging Started...
[11:18:45.837] Alfred Workflow Todoist[Script Filter] Queuing argument ''
[11:18:46.202] Alfred Workflow Todoist[Script Filter] Script with argv '(null)' finished
[11:18:46.205] STDERR: Alfred Workflow Todoist[Script Filter] [ERROR] Invalid API response error: No project with id 1763554177 found
    at nv (/Users/kellyarwine/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.B6EAF5D0-B853-407A-9A88-8CDCEEED19D3/alfred-workflow-todoist.js:29:321308)
    at async /Users/kellyarwine/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.B6EAF5D0-B853-407A-9A88-8CDCEEED19D3/alfred-workflow-todoist.js:29:324596
    at async Promise.all (index 0)
    at async iv (/Users/kellyarwine/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.B6EAF5D0-B853-407A-9A88-8CDCEEED19D3/alfred-workflow-todoist.js:29:326340) {
  name: 'Invalid API response error',
  commonType: 'Invalid API response error',
  description: 'No project with id 1763554177 found',
  title: 'Oops, this is not supposed to happen',
  isSafe: false,
  hide: false,
  url: 'https://github.com/moranje/alfred-workflow-todoist'
}
[11:18:46.207] Alfred Workflow Todoist[Script Filter] {
  "items": [
    {
      "title": "Oops, something is not right",
      "subtitle": "Create a bug report",
      "icon": {
        "path": "icon.png"
      },
      "arg": "{\"name\":\"openUrl\",\"args\":\"https://github.com/moranje/alfred-workflow-todoist/issues/new?body=%23%23%23+Description%0A%0A%3CA+clear+and+concise+description+of+what+the+bug+is.%3E%0A%0A%23%23%23+Steps+to+reproduce+behavior%0A%0A%3CPlease+describe+what+you+did+here.%3E%0A%0A%23%23%23+Expected+behavior%0A%0A%3CA+clear+and+concise+description+of+what+you+expected+to+happen.%3E%0A%0A%23%23%23+Error+logs%0A%0AALFRED+WORKFLOW+TODOIST%0A----------------------------------------%0A_Title_%3A+Oops%2C+this+is+not+supposed+to+happen%0A_Description_%3A+No+project+with+id+1763554177+found%0A%0A_OS_%3A+macOS+10.15.2%0A_Query_%3A+%0A_Node.js_%3A+v13.8.0%0A_Alfred_%3A+4.0.8%0A_Workflow_%3A+6.0.0-debug.1%0A_Workflow-id_%3A+user.workflow.B6EAF5D0-B853-407A-9A88-8CDCEEED19D3%0A%0A_Stack_%3A+Invalid+API+response+error%3A+No+project+with+id+1763554177+found%0A++++at+nv+%28%2FUsers%2Fkellyarwine%2FLibrary%2FApplication+Support%2FAlfred%2FAlfred.alfredpreferences%2Fworkflows%2Fuser.workflow.B6EAF5D0-B853-407A-9A88-8CDCEEED19D3%2Falfred-workflow-todoist.js%3A29%3A321308%29%0A++++at+async+%2FUsers%2Fkellyarwine%2FLibrary%2FApplication+Support%2FAlfred%2FAlfred.alfredpreferences%2Fworkflows%2Fuser.workflow.B6EAF5D0-B853-407A-9A88-8CDCEEED19D3%2Falfred-workflow-todoist.js%3A29%3A324596%0A++++at+async+Promise.all+%28index+0%29%0A++++at+async+iv+%28%2FUsers%2Fkellyarwine%2FLibrary%2FApplication+Support%2FAlfred%2FAlfred.alfredpreferences%2Fworkflows%2Fuser.workflow.B6EAF5D0-B853-407A-9A88-8CDCEEED19D3%2Falfred-workflow-todoist.js%3A29%3A326340%29&title=%5BBug%5D+Invalid+API+response+error%3A+No+project+with+id+1763554177+found\"}",
      "type": "default",
      "valid": true,
      "quicklookurl": "https://github.com/moranje/alfred-workflow-todoist/issues/new?body=%23%23%23+Description%0A%0A%3CA+clear+and+concise+description+of+what+the+bug+is.%3E%0A%0A%23%23%23+Steps+to+reproduce+behavior%0A%0A%3CPlease+describe+what+you+did+here.%3E%0A%0A%23%23%23+Expected+behavior%0A%0A%3CA+clear+and+concise+description+of+what+you+expected+to+happen.%3E%0A%0A%23%23%23+Error+logs%0A%0AALFRED+WORKFLOW+TODOIST%0A----------------------------------------%0A_Title_%3A+Oops%2C+this+is+not+supposed+to+happen%0A_Description_%3A+No+project+with+id+1763554177+found%0A%0A_OS_%3A+macOS+10.15.2%0A_Query_%3A+%0A_Node.js_%3A+v13.8.0%0A_Alfred_%3A+4.0.8%0A_Workflow_%3A+6.0.0-debug.1%0A_Workflow-id_%3A+user.workflow.B6EAF5D0-B853-407A-9A88-8CDCEEED19D3%0A%0A_Stack_%3A+Invalid+API+response+error%3A+No+project+with+id+1763554177+found%0A++++at+nv+%28%2FUsers%2Fkellyarwine%2FLibrary%2FApplication+Support%2FAlfred%2FAlfred.alfredpreferences%2Fworkflows%2Fuser.workflow.B6EAF5D0-B853-407A-9A88-8CDCEEED19D3%2Falfred-workflow-todoist.js%3A29%3A321308%29%0A++++at+async+%2FUsers%2Fkellyarwine%2FLibrary%2FApplication+Support%2FAlfred%2FAlfred.alfredpreferences%2Fworkflows%2Fuser.workflow.B6EAF5D0-B853-407A-9A88-8CDCEEED19D3%2Falfred-workflow-todoist.js%3A29%3A324596%0A++++at+async+Promise.all+%28index+0%29%0A++++at+async+iv+%28%2FUsers%2Fkellyarwine%2FLibrary%2FApplication+Support%2FAlfred%2FAlfred.alfredpreferences%2Fworkflows%2Fuser.workflow.B6EAF5D0-B853-407A-9A88-8CDCEEED19D3%2Falfred-workflow-todoist.js%3A29%3A326340%29&title=%5BBug%5D+Invalid+API+response+error%3A+No+project+with+id+1763554177+found"
    }
  ]
}```

**Comment by moranje** [comment]
That's what I expected, still nothing off. Can you see if anything is weird the the name of that [project](https://todoist.com/app#project%2F1763554177). Anything else off?

**Comment by kellyarwine** [comment]
Interesting, that is an old archived product.  I figured it would be my inbox.  How does it pick up that ID?

Other notable things:

* Node was installed with Homebrew
* [I have some Node configurations set up.  Maybe I shouldn't?](https://www.screencast.com/t/yBBqAXbKkm4t)

**Comment by moranje** [comment]
I'm able to reproduce the error now, when I create a cached task with a reference to an archived project. That makes a lot of sense, thanks for your help!

**Comment by kellyarwine** [comment]
Awesome, so should I just wait for a new release to be published?

**Comment by moranje** [comment]
Yes, I'll post a new update soon!

**Comment by kellyarwine** [comment]
:) It didn't work.  I got the `REFRESH CACHE` to come up but tried `todos` afterwards and get the same error (same project ID).  No problem waiting until a new release comes out though.  Thank you again.

**Comment by moranje** [comment]
That sounds like I've solved another unrelated bug then. I've build you another version with the bug fix baked in. I also put in a few more log statements. These will only show up if you set `todo:setting log_level debug`. Based on your previous comment I'm afraid it may be bugsy still... It breaks my head.

### v6.0.0-debug.2

[Alfred Workflow Todoist.zip](https://github.com/moranje/alfred-workflow-todoist/files/4320882/Alfred.Workflow.Todoist.zip)

**Comment by kellyarwine** [comment]
Thank you!  Something different definitely happened.  It seems to not still reset the cache but I got a different log:
```[18:47:38.170] Alfred Workflow Todoist[Script Filter] Queuing argument ''
[18:47:39.873] Alfred Workflow Todoist[Script Filter] Script with argv '(null)' finished
[18:47:39.876] STDERR: Alfred Workflow Todoist[Script Filter] [DEBUG] CREATE TASK VIEW {
  id: 3613847015,
  project_id: 1763554177,
  section_id: 0,
  order: 1,
  content: 'PM Showers/Wind! Bring an umbrella',
  completed: false,
  label_ids: [],
  priority: 1,
  comment_count: 1,
  created: '2020-01-08T16:49:24Z',
  due: {
    recurring: false,
    string: 'Jan 9 8:00 AM',
    date: '2020-01-09',
    datetime: '2020-01-09T14:00:00Z',
    timezone: 'America/Chicago'
  },
  url: 'https://todoist.com/showTask?id=3613847015'
}
[DEBUG] CREATE TASK VIEW {
  id: 3615080005,
  project_id: 1763554177,
  section_id: 0,
  order: 2,
  content: 'Rain! Bring an umbrella',
  completed: false,
  label_ids: [],
  priority: 1,
  comment_count: 1,
  created: '2020-01-09T06:49:04Z',
  due: {
    recurring: false,
    string: 'Jan 10 8:00 AM',
    date: '2020-01-10',
    datetime: '2020-01-10T14:00:00Z',
    timezone: 'America/Chicago'
  },
  url: 'https://todoist.com/showTask?id=3615080005'
}
[DEBUG] CREATE TASK VIEW {
  id: 3617469900,
  project_id: 1763554177,
  section_id: 0,
  order: 3,
  content: 'Rain/Snow/Wind! Bring an umbrella',
  completed: false,
  label_ids: [],
  priority: 1,
  comment_count: 1,
  created: '2020-01-10T06:49:25Z',
  due: {
    recurring: false,
    string: 'Jan 11 8:00 AM',
    date: '2020-01-11',
    datetime: '2020-01-11T14:00:00Z',
    timezone: 'America/Chicago'
  },
  url: 'https://todoist.com/showTask?id=3617469900'
}
[DEBUG] CREATE TASK VIEW {
  id: 3625415937,
  project_id: 1763554177,
  section_id: 0,
  order: 4,
  content: 'AM Showers! Bring an umbrella',
  completed: false,
  label_ids: [],
  priority: 1,
  comment_count: 1,
  created: '2020-01-14T06:49:27Z',
  due: {
    recurring: false,
    string: 'Jan 15 8:00 AM',
    date: '2020-01-15',
    datetime: '2020-01-15T14:00:00Z',
    timezone: 'America/Chicago'
  },
  url: 'https://todoist.com/showTask?id=3625415937'
}
[DEBUG] CREATE TASK VIEW {
  id: 3632620657,
  project_id: 1763554177,
  section_id: 0,
  order: 5,
  content: 'AM Rain/Snow/Wind! Bring an umbrella',
  completed: false,
  label_ids: [],
  priority: 1,
  comment_count: 1,
  created: '2020-01-17T06:49:27Z',
  due: {
    recurring: false,
    string: 'Jan 18 8:00 AM',
    date: '2020-01-18',
    datetime: '2020-01-18T14:00:00Z',
    timezone: 'America/Chicago'
  },
  url: 'https://todoist.com/showTask?id=3632620657'
}
[DEBUG] CREATE TASK VIEW {
  id: 3645141785,
  project_id: 1763554177,
  section_id: 0,
  order: 6,
  content: 'Rain/Snow! Bring an umbrella',
  completed: false,
  label_ids: [],
  priority: 1,
  comment_count: 1,
  created: '2020-01-23T06:49:25Z',
  due: {
    recurring: false,
    string: 'Jan 23 8:00 AM',
    date: '2020-01-23',
    datetime: '2020-01-23T16:00:00Z',
    timezone: 'America/Los_Angeles'
  },
  url: 'https://todoist.com/showTask?id=3645141785'
}
[DEBUG] CREATE TASK VIEW {
  id: 3680002727,
  project_id: 1763554177,
  section_id: 0,
  order: 7,
  content: 'Rain/Snow! Bring an umbrella',
  completed: false,
  label_ids: [],
  priority: 1,
  comment_count: 1,
  created: '2020-02-08T22:49:29Z',
  due: {
    recurring: false,
    string: 'Feb 9 8:00 AM',
    date: '2020-02-09',
    datetime: '2020-02-09T14:00:00Z',
    timezone: 'America/Chicago'
  },
  url: 'https://todoist.com/showTask?id=3680002727'
}
[DEBUG] CREATE TASK VIEW {
  id: 3694899033,
  project_id: 1763554177,
  section_id: 0,
  order: 8,
  content: 'PM Showers! Bring an umbrella',
  completed: false,
  label_ids: [],
  priority: 1,
  comment_count: 1,
  created: '2020-02-16T06:49:27Z',
  due: {
    recurring: false,
    string: 'Feb 17 8:00 AM',
    date: '2020-02-17',
    datetime: '2020-02-17T14:00:00Z',
    timezone: 'America/Chicago'
  },
  url: 'https://todoist.com/showTask?id=3694899033'
}
[DEBUG] CREATE TASK VIEW {
  id: 3709471334,
  project_id: 1763554177,
  section_id: 0,
  order: 9,
  content: 'PM Light Rain! Bring an umbrella',
  completed: false,
  label_ids: [],
  priority: 1,
  comment_count: 1,
  created: '2020-02-23T06:49:27Z',
  due: {
    recurring: false,
    string: 'Feb 24 8:00 AM',
    date: '2020-02-24',
    datetime: '2020-02-24T14:00:00Z',
    timezone: 'America/Chicago'
  },
  url: 'https://todoist.com/showTask?id=3709471334'
}
[DEBUG] No project with id 1763554177 found, this probably means a cached task holds a reference to a deleted project.
[DEBUG] No project with id 1763554177 found, this probably means a cached task holds a reference to a deleted project.
[DEBUG] No project with id 1763554177 found, this probably means a cached task holds a reference to a deleted project.
[DEBUG] No project with id 1763554177 found, this probably means a cached task holds a reference to a deleted project.
[DEBUG] No project with id 1763554177 found, this probably means a cached task holds a reference to a deleted project.
[DEBUG] No project with id 1763554177 found, this probably means a cached task holds a reference to a deleted project.
[DEBUG] No project with id 1763554177 found, this probably means a cached task holds a reference to a deleted project.
[DEBUG] No project with id 1763554177 found, this probably means a cached task holds a reference to a deleted project.
[DEBUG] No project with id 1763554177 found, this probably means a cached task holds a reference to a deleted project.
[ERROR] Invalid cache: The task cache was out of sync with Todoist, which should be fixed now. Please try again.
    at nv (/Users/kellyarwine/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.B6EAF5D0-B853-407A-9A88-8CDCEEED19D3/alfred-workflow-todoist.js:29:321644)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async /Users/kellyarwine/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.B6EAF5D0-B853-407A-9A88-8CDCEEED19D3/alfred-workflow-todoist.js:29:325561
    at async Promise.all (index 2)
    at async iv (/Users/kellyarwine/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.B6EAF5D0-B853-407A-9A88-8CDCEEED19D3/alfred-workflow-todoist.js:29:327305) {
  name: 'Invalid cache',
  commonType: 'Invalid cache',
  description: 'The task cache was out of sync with Todoist, which should be fixed now. Please try again.',
  title: 'Oops, this is not supposed to happen',
  isSafe: true,
  hide: false,
  url: 'https://github.com/moranje/alfred-workflow-todoist'
}
[18:47:39.882] Alfred Workflow Todoist[Script Filter] {
  "items": [
    {
      "title": "Oops, this is not supposed to happen",
      "subtitle": "The task cache was out of sync with Todoist, which should be fixed now. Please try again.",
      "icon": {
        "path": "icon.png"
      },
      "arg": "{\"name\":\"openUrl\",\"args\":\"https://github.com/moranje/alfred-workflow-todoist\"}",
      "type": "default",
      "valid": true,
      "text": {
        "copy": "Invalid cache: The task cache was out of sync with Todoist, which should be fixed now. Please try again."
      },
      "quicklookurl": "https://github.com/moranje/alfred-workflow-todoist"
    }
  ]
}```

**Comment by moranje** [comment]
That helps! Looks like an IFTTT that connects WeatherUnderground to Todoist, right? I've created a applet to see if I can reproduce. A couple questions:

1. Is that project indeed archived? 
2. What is the name of the project?
3. Do these tasks appear archived as well in the Todoist app?
4. What did you use to archive the project (web/desktop/phone/API call)

Thanks Kelly!

**Comment by kellyarwine** [comment]
Hi, @moranje.  We're making progress!  Yes, those tasks were oddly from Weather Underground IFTTT.  Interesting as they were writing to an archived project??  Seems like a bug.  I checked by configuration and have "Inbox" as the category.

So I deleted all of those tasks to move on from the issue.  Now we're making more progress but I still get the same error.  Here's the log:

```[12:43:40.275] Alfred Workflow Todoist[Script Filter] Queuing argument ''
[12:43:40.924] Alfred Workflow Todoist[Script Filter] Script with argv '(null)' finished
[12:43:40.926] STDERR: Alfred Workflow Todoist[Script Filter] [DEBUG] CREATE TASK VIEW {
  id: 3681913520,
  project_id: 2177515994,
  section_id: 0,
  order: 5,
  OMITTED,
  completed: false,
  label_ids: [],
  priority: 2,
  comment_count: 0,
  created: '2020-02-10T05:21:34Z',
  due: { recurring: false, string: 'Mar 12', date: '2020-03-12' },
  url: 'https://todoist.com/showTask?id=3681913520'
}
[DEBUG] CREATE TASK VIEW {
  id: 3742147228,
  project_id: 2177515994,
  section_id: 0,
  order: 13,
  OMITTED,
  completed: false,
  label_ids: [],
  priority: 2,
  comment_count: 0,
  created: '2020-03-09T16:47:08Z',
  due: { recurring: false, string: 'Mar 12', date: '2020-03-12' },
  url: 'https://todoist.com/showTask?id=3742147228'
}
[DEBUG] CREATE TASK VIEW {
  id: 3742148315,
  project_id: 2177515994,
  section_id: 0,
  order: 14,
  OMITTED,
  completed: false,
  label_ids: [],
  priority: 2,
  comment_count: 1,
  created: '2020-03-09T16:47:31Z',
  due: { recurring: false, string: 'Mar 12', date: '2020-03-12' },
  url: 'https://todoist.com/showTask?id=3742148315'
}
[DEBUG] CREATE TASK VIEW {
  id: 3742176806,
  project_id: 2177515994,
  section_id: 0,
  order: 11,
  OMITTED,
  completed: false,
  label_ids: [],
  priority: 2,
  comment_count: 0,
  created: '2020-03-09T16:58:37Z',
  due: { recurring: false, string: 'Mar 12', date: '2020-03-12' },
  url: 'https://todoist.com/showTask?id=3742176806'
}
[DEBUG] CREATE TASK VIEW {
  id: 3742177682,
  project_id: 2177515994,
  section_id: 0,
  order: 12,
  OMITTED,
  completed: false,
  label_ids: [],
  priority: 2,
  comment_count: 0,
  created: '2020-03-09T16:58:52Z',
  due: { recurring: false, string: 'Mar 12', date: '2020-03-12' },
  url: 'https://todoist.com/showTask?id=3742177682'
}
[DEBUG] CREATE TASK VIEW {
  id: 3744395927,
  project_id: 2231052592,
  section_id: 0,
  order: 1,
  content: "[ Dependent PR's use case @AMD ](https://mail.google.com/mail/u/0/#inbox/FMfcgxwHMGBGLSZzXndxRqmLxmVgPzMM)",
  completed: false,
  label_ids: [],
  priority: 3,
  comment_count: 0,
  created: '2020-03-10T15:30:38Z',
  due: { recurring: false, string: 'Mar 12', date: '2020-03-12' },
  url: 'https://todoist.com/showTask?id=3744395927'
}
[DEBUG] CREATE TASK VIEW {
  id: 3744924877,
  project_id: 2177515994,
  section_id: 0,
  order: 15,
  OMITTED,
  completed: false,
  label_ids: [],
  priority: 3,
  comment_count: 0,
  created: '2020-03-10T19:33:53Z',
  due: { recurring: false, string: 'Mar 12', date: '2020-03-12' },
  url: 'https://todoist.com/showTask?id=3744924877'
}
[DEBUG] CREATE TASK VIEW {
  id: 3744925011,
  project_id: 2177515994,
  section_id: 0,
  order: 16,
  OMITTED,
  completed: false,
  label_ids: [],
  priority: 3,
  comment_count: 0,
  created: '2020-03-10T19:33:59Z',
  due: { recurring: false, string: 'Mar 12', date: '2020-03-12' },
  url: 'https://todoist.com/showTask?id=3744925011'
}
[DEBUG] CREATE TASK VIEW {
  id: 3639010567,
  project_id: 2217655286,
  section_id: 0,
  order: 18,
  OMITTED,
  completed: false,
  label_ids: [],
  priority: 2,
  comment_count: 0,
  created: '2020-01-20T17:01:24Z',
  due: { recurring: true, string: 'every 28 days', date: '2020-03-13' },
  url: 'https://todoist.com/showTask?id=3639010567'
}
[DEBUG] No project with id 2231052592 found, this probably means a cached task holds a reference to a deleted project.
[ERROR] Invalid cache: The task cache was out of sync with Todoist, which should be fixed now. Please try again.
    at nv (/Users/kellyarwine/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.B6EAF5D0-B853-407A-9A88-8CDCEEED19D3/alfred-workflow-todoist.js:29:321644)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async /Users/kellyarwine/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.B6EAF5D0-B853-407A-9A88-8CDCEEED19D3/alfred-workflow-todoist.js:29:325561
    at async Promise.all (index 5)
    at async iv (/Users/kellyarwine/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.B6EAF5D0-B853-407A-9A88-8CDCEEED19D3/alfred-workflow-todoist.js:29:327305) {
  name: 'Invalid cache',
  commonType: 'Invalid cache',
  description: 'The task cache was out of sync with Todoist, which should be fixed now. Please try again.',
  title: 'Oops, this is not supposed to happen',
  isSafe: true,
  hide: false,
  url: 'https://github.com/moranje/alfred-workflow-todoist'
}
[12:43:40.932] Alfred Workflow Todoist[Script Filter] {
  "items": [
    {
      "title": "Oops, this is not supposed to happen",
      "subtitle": "The task cache was out of sync with Todoist, which should be fixed now. Please try again.",
      "icon": {
        "path": "icon.png"
      },
      "arg": "{\"name\":\"openUrl\",\"args\":\"https://github.com/moranje/alfred-workflow-todoist\"}",
      "type": "default",
      "valid": true,
      "text": {
        "copy": "Invalid cache: The task cache was out of sync with Todoist, which should be fixed now. Please try again."
      },
      "quicklookurl": "https://github.com/moranje/alfred-workflow-todoist"
    }
  ]
}```

The project in question IS a project I created last night.  I tried updating cache but it doesn't seem to have helped.  I get the same error.  Thoughts?

**Comment by moranje** [comment]
Hi Kelly,

Sorry for not responding earlier. Life got a little hectic here. I've been pondering a fix but haven't had time to sit down and implement it. I'll post it here as soon as I get a chance. Stay healthy,

Martien

**Comment by kellyarwine** [comment]
Just FYI, @moranje the `todos` command started working!  Should we just consider this closed?

On another note, the command pulls up a bunch of completed tasks (and not the ones I just marked complete).  Is that what it's supposed to do?

**Comment by moranje** [comment]
Haha, magical! So do you happen to be a premium user? if so you could try:

`todos "search: <query>"`

Where `<query>` would be what you normally type after `todos`. You'd query without hitting the cache. It sounds like it's either a cache problem or a problem with the REST API by Todoist.

Martien

**Comment by kellyarwine** [comment]
Here's what I get.  I added a task called "make coffee" to the Inbox.  If I run your suggested command, this comes up:
![image](https://user-images.githubusercontent.com/2262535/77436887-02fd9180-6db2-11ea-9630-015b965f3442.png)

I'm confused about what I'm looking at.  Is this the intent?  Search a task and hit "Enter" and the task will complete?  The readme was short on details.

If so, it looks like it might be working. If so, I think we can close out this issue.

**Comment by moranje** [comment]
Yes that seems to be working as intended. Although searching in quotes is meant for using filters (same as in the Todoist app) and bypasses the cache. Normally `todos make coffee` is preferred and much faster. You can fiddle around with the cache options in settings. If `todos make coffee` works for you as well thanks I agree, lets close this issue.

Thanks for your patience, I hope to be able to release a stable version soon.

Martien

**Comment by kellyarwine** [comment]
Done!  Thanks for all the help.  And thanks for the workflow.  I probably use it 30 times a day (big user of Todoist).
