### ISSUE TITLE
[Bug] TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by ggnall** [moranje/alfred-workflow-todoist#167]
### Description

Issue creating tasks on first install.

### Steps to reproduce behavior

1. Installed workflow. (Have tried master, beta, and now alpha).
2. Configured (set token, node location)
3. Try to create a task

Looks like I'm not able to set anything with my input.

### Expected behavior

Task is created.

### Error logs

ALFRED WORKFLOW TODOIST
----------------------------------------
_Title_: TypeError
_Description_: Cannot convert undefined or null to object

_OS_: macOS 10.15.3
_Query_: [object Object]
_Node.js_: v12.16.2
_Alfred_: 3.8.6
_Workflow_: 6.0.0-alpha.10
_Workflow-id_: user.workflow.9E6A533E-64D9-48B3-8285-512C0B0D044A

_Stack_: TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Object.set store [as store] (/Users/gg/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.9E6A533E-64D9-48B3-8285-512C0B0D044A/alfred-workflow-todoist.js:29:182787)
    at Bh.qh [as deserialize] (/Users/gg/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.9E6A533E-64D9-48B3-8285-512C0B0D044A/alfred-workflow-todoist.js:29:183491)
    at Bh.get store [as store] (/Users/gg/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.9E6A533E-64D9-48B3-8285-512C0B0D044A/alfred-workflow-todoist.js:15:123392)
    at new e.exports (/Users/gg/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.9E6A533E-64D9-48B3-8285-512C0B0D044A/alfred-workflow-todoist.js:15:119010)
    at new Bh (/Users/gg/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.9E6A533E-64D9-48B3-8285-512C0B0D044A/alfred-workflow-todoist.js:29:183708)
    at /Users/gg/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.9E6A533E-64D9-48B3-8285-512C0B0D044A/alfred-workflow-todoist.js:29:210707
    at tp (/Users/gg/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.9E6A533E-64D9-48B3-8285-512C0B0D044A/alfred-workflow-todoist.js:29:211001)
    at /Users/gg/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.9E6A533E-64D9-48B3-8285-512C0B0D044A/alfred-workflow-todoist.js:29:329772
    at wv (/Users/gg/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.9E6A533E-64D9-48B3-8285-512C0B0D044A/alfred-workflow-todoist.js:29:329979)

**Comment by moranje** [comment]
Is this bug still in the latest beta?

**Comment by ggnall** [comment]
Yes in both beta and alpha via: https://github.com/moranje/alfred-workflow-todoist/releases

I'm not sure if there's something wrong with my node setup

**Comment by bstascavage** [comment]
I am seeing the same issue, BTW.  Maybe todoist updated something on their end?

**Comment by mrokaini** [comment]
I have the same issue on the first install and the API request is not connecting with todoist.

**Comment by Dramaturco** [comment]
I have the same issue with 6.0.0-alpha10 

I tried multiple different node setups because I thought it might have something to do with that.

**Comment by jakubka** [comment]
Same with this setup:

_OS_: macOS 10.15.5
_Query_: [object Object]
_Node.js_: v12.13.0
_Alfred_: 3.8.6
_Workflow_: 6.0.0-beta.1
_Workflow-id_: user.workflow.0FF47443-16F9-4F1F-9287-59C0D0791DC5

**Comment by altosaar** [comment]
Same here
