### ISSUE TITLE
[Bug] TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by Robis74** [moranje/alfred-workflow-todoist#186]
### Description

Pretty new to Alfred, ToDoIst and not a programmer! So no idea how to get this working... I got as far as adding my API token from ToDoIst, but that's about it... Installed Node JS by just clicking through it. Added a screenshot of my terminal if that helps...
![Screenshot 2020-10-30 at 17 25 36](https://user-images.githubusercontent.com/73709611/97731103-04740280-1ad5-11eb-9d1c-b823f7d930ed.png)

### Steps to reproduce behavior

Tried to create a task: 
"todo car wash today"

### Expected behavior

Task should have been added to my todoist but instead got an error message. 

### Error logs

ALFRED WORKFLOW TODOIST
----------------------------------------
_Title_: TypeError
_Description_: Cannot convert undefined or null to object

_OS_: macOS 10.15.7
_Query_: [object Object]
_Node.js_: v14.15.0
_Alfred_: 3.8.6
_Workflow_: 6.0.0-beta.1
_Workflow-id_: user.workflow.07BACD74-A025-495B-91B4-39F0CBCDE377

_Stack_: TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Object.set store [as store] (/Users/mac/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.07BACD74-A025-495B-91B4-39F0CBCDE377/alfred-workflow-todoist.js:29:182781)
    at Bh.qh [as deserialize] (/Users/mac/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.07BACD74-A025-495B-91B4-39F0CBCDE377/alfred-workflow-todoist.js:29:183485)
    at Bh.get store [as store] (/Users/mac/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.07BACD74-A025-495B-91B4-39F0CBCDE377/alfred-workflow-todoist.js:15:123392)
    at new e.exports (/Users/mac/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.07BACD74-A025-495B-91B4-39F0CBCDE377/alfred-workflow-todoist.js:15:119010)
    at new Bh (/Users/mac/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.07BACD74-A025-495B-91B4-39F0CBCDE377/alfred-workflow-todoist.js:29:183702)
    at /Users/mac/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.07BACD74-A025-495B-91B4-39F0CBCDE377/alfred-workflow-todoist.js:29:210701
    at tp (/Users/mac/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.07BACD74-A025-495B-91B4-39F0CBCDE377/alfred-workflow-todoist.js:29:210995)
    at /Users/mac/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.07BACD74-A025-495B-91B4-39F0CBCDE377/alfred-workflow-todoist.js:29:329760
    at wv (/Users/mac/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.07BACD74-A025-495B-91B4-39F0CBCDE377/alfred-workflow-todoist.js:29:329967)

**Comment by samlcharreyron** [comment]
I have the same with 6.0.0-beta1
