### ISSUE TITLE
HTTPError: Response code 410 (Gone)

### ISSUE THREAD

**Issue by Stooovie** [moranje/alfred-workflow-todoist#216]
Hi, I'm getting HTTPError: Response code 410 (Gone) when doing anything with this workflow.

Here's an example at trying to create a new task:

`[09:27:00.025] Alfred Workflow Todoist[Debug] 'Error log [Arguments] {
  '0': HTTPError: Response code 410 (Gone)
      at EventEmitter.<anonymous> (/Users/stooovie/SynologyDrive/Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.1DD91EF0-6B8A-44C2-A5E8-01FD58179DCF/alfred-workflow-todoist.js:40858:19)
      at processTicksAndRejections (node:internal/process/task_queues:96:5) {
    host: undefined,
    hostname: 'beta.todoist.com',
    method: 'GET',
    path: '/API/v8/projects',
    socketPath: undefined,
    protocol: 'https:',
    url: 'https://beta.todoist.com/API/v8/projects',
    statusCode: 410,
    statusMessage: 'Gone',
    headers: {
      'content-type': 'text/plain; charset=utf-8',
      'content-length': '109',
      connection: 'close',
      server: 'awselb/2.0',
      date: 'Wed, 13 Oct 2021 07:26:54 GMT',
      'x-cache': 'Error from cloudfront',
      via: '1.1 2af4ee189e50805a67bd62bbd51ad0dc.cloudfront.net (CloudFront)',
      'x-amz-cf-pop': 'FRA56-P2',
      'x-amz-cf-id': 'v_bEN091f2_AnrOcGXgewZwb0yopxk5PPD_jij3_grXvSWXGREHFmw=='
    }
  }
}
HTTPError: Response code 410 (Gone)

ALFRED WORKFLOW TODOIST
----------------------------------------
os: macOS
query: {"content":"mrd","priority":1}
node.js: v16.11.1
alfred: unknown
workflow: 5.6.1
Stack: HTTPError: Response code 410 (Gone)
    at EventEmitter.<anonymous> (/Users/stooovie/SynologyDrive/Settings/Alfred/Alfred.alfredpreferences/workflows/user.workflow.1DD91EF0-6B8A-44C2-A5E8-01FD58179DCF/alfred-workflow-todoist.js:40858:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
', {}`

**Comment by joshvickerson** [comment]
I'm also having this issue. @Stooovie were you able to resolve this somehow?

**Comment by moranje** [comment]
Download the latest beta, that should fix the problem.

---
Martien

**Comment by Stooovie** [comment]
Great, works, thanks! Any idea how to set a default list? I use Todoist the most for Amazon Alexa Shopping lists, which is its own list in Todoist. I'd love to be able to set it as default so that when I add new task via Alfred, it goes right to this list.
