### ISSUE TITLE
Stack: Error: spawn Unknown system error -86

### ISSUE THREAD

**Issue by baptisteArno** [moranje/alfred-workflow-todoist#217]
### Description

I'm trying to configure the workflow but it crashes instantly. I tried several node versions.

### Steps to reproduce

1. Alfred input 'todo:setting'
2. See error

### Error logs

Log:

```
ALFRED WORKFLOW TODOIST
----------------------------------------
os: macOS 12.0.0
query: 
node.js: v14.18.1
alfred: unknown
workflow: 5.8.3
Stack: Error: spawn Unknown system error -86
    at ChildProcess.spawn (internal/child_process.js:405:11)
    at spawn (child_process.js:677:9)
    at Object.spawnWithSignal [as spawn] (child_process.js:911:17)
    at notify$1 (/Users/baptistearno/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.4F8A53CF-CAE6-4563-A940-72F641979E7D/alfred-workflow-todoist.js:9167:31)
    at Object.write (/Users/baptistearno/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.4F8A53CF-CAE6-4563-A940-72F641979E7D/alfred-workflow-todoist.js:9225:24)
    at process.handleError (/Users/baptistearno/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.4F8A53CF-CAE6-4563-A940-72F641979E7D/alfred-workflow-todoist.js:9286:65)
    at process.emit (events.js:400:28)
    at processPromiseRejections (internal/process/promises.js:245:33)
    at processTicksAndRejections (internal/process/task_queues.js:96:32)
```

### Additional context
I'm on a M1 Macbook. Could that cause an issue? 🤔

**Comment by moranje** [comment]
Not entirely sure, I don't own an M1 mac (yet). Make sure you are one the latest beta.
