### ISSUE TITLE
unable to get local issuer certificate?

### ISSUE THREAD

**Issue by ainaimi** [moranje/alfred-workflow-todoist#221]
### Description

Thanks for this putting this workflow together. I've used it successfully (and extensively) in the past. After migrating to a new laptop I can't seem to get any of the functions to work. The problem always results in an "issuer certificate" problem, and I don't know how to solve it.

### Steps to reproduce

After installing the workflow, node, and setting the API, I call alfred and type: `todo test`. Nothing happens. 

When I run the debugger in Alfred, I get an error stating: "unable to get local issuer certificate"

Any thoughts? Am I doing something wrong?

Thanks!

### Error logs

[17:24:27.492] Logging Started...
[17:24:34.580] Alfred Workflow Todoist[Script Filter] Queuing argument 't'
[17:24:34.665] Alfred Workflow Todoist[Script Filter] Queuing argument 'te'
[17:24:34.802] Alfred Workflow Todoist[Script Filter] Script with argv '(null)' finished
[17:24:34.805] Alfred Workflow Todoist[Script Filter] {
  "items": [
    {
      "title": "ADD TASK: t",
      "subtitle": "INBOX",
      "icon": {
        "path": "icon.png"
      },
      "arg": "{\"name\":\"create\",\"args\":{\"content\":\"t\",\"label_ids\":[],\"due_lang\":\"en\"}}",
      "type": "default",
      "valid": true
    }
  ]
}
[17:24:34.859] Alfred Workflow Todoist[Script Filter] Queuing argument 'tes'
[17:24:34.960] Alfred Workflow Todoist[Script Filter] Queuing argument 'test'
[17:24:34.984] Alfred Workflow Todoist[Script Filter] Script with argv '(null)' finished
[17:24:34.987] Alfred Workflow Todoist[Script Filter] {
  "items": [
    {
      "title": "ADD TASK: te",
      "subtitle": "INBOX",
      "icon": {
        "path": "icon.png"
      },
      "arg": "{\"name\":\"create\",\"args\":{\"content\":\"te\",\"label_ids\":[],\"due_lang\":\"en\"}}",
      "type": "default",
      "valid": true
    }
  ]
}
[17:24:35.104] Alfred Workflow Todoist[Script Filter] Script with argv '(null)' finished
[17:24:35.109] Alfred Workflow Todoist[Script Filter] {
  "items": [
    {
      "title": "ADD TASK: test",
      "subtitle": "INBOX",
      "icon": {
        "path": "icon.png"
      },
      "arg": "{\"name\":\"create\",\"args\":{\"content\":\"test\",\"label_ids\":[],\"due_lang\":\"en\"}}",
      "type": "default",
      "valid": true
    }
  ]
}
[17:24:35.869] Alfred Workflow Todoist[Script Filter] Processing complete
[17:24:35.870] Alfred Workflow Todoist[Script Filter] Passing output '{"name":"create","args":{"content":"test","label_ids":[],"due_lang":"en"}}' to Run Script
[17:24:36.053] STDERR: Alfred Workflow Todoist[Run Script] [ERROR] Todoist API error (RequestError): unable to get local issuer certificate
    at rp (/Users/ain/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.34D531C3-A0F2-4F09-8C0F-0CC510C5BFF2/alfred-workflow-todoist.js:29:211455)
    at /Users/ain/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.34D531C3-A0F2-4F09-8C0F-0CC510C5BFF2/alfred-workflow-todoist.js:29:329799
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /Users/ain/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.34D531C3-A0F2-4F09-8C0F-0CC510C5BFF2/alfred-workflow-todoist.js:29:329754 {
  commonType: 'Todoist API error',
  description: 'unable to get local issuer certificate',
  title: 'The request to the API failed',
  isSafe: true,
  hide: false,
  url: 'https://github.com/moranje/alfred-workflow-todoist'
}
[17:24:36.062] Alfred Workflow Todoist[Run Script] Processing complete
[17:24:36.062] Alfred Workflow Todoist[Run Script] Passing output '' to Debug
[17:24:36.062] Alfred Workflow Todoist[Debug] '', {
  node_flags = ""
  node_path = ""
}
[17:33:05.799] Logging Stopped.

```
ALFRED WORKFLOW TODOIST
----------------------------------------
os: macOS 11.6.2
query: {"content":"<title>","priority":1}
node.js: 17.4.0
alfred: 4.6.2
workflow: 6.0.0-beta.1
Stack: HTTPError: Response code 400 (Bad Request)
 ...
```

### Additional context

Happy to provide additional context, let me know!

**Comment by moranje** [comment]
I haven't been active on the project for a while so I might be off, but that sounds like a general problem with an SSL certificate. Maybe todoist was having problems?
