### ISSUE TITLE
Can't configure workflow

### ISSUE THREAD

**Issue by xTimpi** [moranje/alfred-workflow-todoist#51]
### Describe the bug

After downloading the workflow, the given configuration steps are not working

### Steps to reproduce

Download the workflow, type todo:setting  token <token>

### Expected behavior

set the token as workflow config

#### Alfred debugger

[2018-11-26 16:32:47][ERROR: input.scriptfilter] Code 1: /Users/Timpi/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.BCBD9574-3DE4-4B5C-A686-8DDD0D2FE3F3/alfred-workflow-todoist.js:39872
				url = normalizeUrlObject({ ...opts, pathname, search });
				                           ^^^
SyntaxError: Unexpected token ...
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

EDIT:
same behaviour for every configuration option

thanks for your time

**Comment by moranje** [comment]
What versions of the workflow and what version of node are you on?

**Comment by xTimpi** [comment]
node: 10.13.0

workflow: latest release downloaded yesterday from
https://github.com/moranje/alfred-workflow-todoist/raw/master/dist/Alfred%20Workflow%20Todoist.alfredworkflow

**Comment by xTimpi** [comment]
### found the problem
apparently alfred does not play well with [nvm](https://github.com/creationix/nvm), event though my terminal reported version 10.13.0 only after I installed node via brew, the issue was resolved.

feel free to close this issue

**Comment by moranje** [comment]
For future reference, what version of node did the workflow die on?

**Comment by xTimpi** [comment]
it was 9.8.0

**Comment by moranje** [comment]
Good to know! Thanks for reporting back.

-- 
Martien Oranje

Op 28 november 2018 bij 16:03:27, Tim P (notifications@github.com) schreef:

it was 9.8.0

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/moranje/alfred-workflow-todoist/issues/51#issuecomment-442477985>,
or mute the thread
